### ISSUE TITLE
Bug: wrong query parameter encoding and missing trailing slash when fetching access token

### ISSUE THREAD

**Issue by yanmorinokamca** [wpengine/faustjs#1018]
## Applicable Versions

- `@faustjs/core` version: current github version (2022-09-13)

## Steps To Reproduce

1. Use fechAccessToken() from faustjs core, by passing useLogin(). We use a custom loginMutation function.
2. Setup with trailingSlash: true in next.config.js

Link to code example:
https://github.com/wpengine/faustjs/blob/canary/packages/core/src/auth/client/accessToken.ts#L139

## The current behavior
In fetchAccessToken, the url doesn't contains a trailing slash, and this cause an HTTP redirect 308.

In fetchAccessToken, `?code=${code}` is not encoded with encodeURIComponent and could cause problem with "+" and other special characters, we can see the "+" converted to " " (space) in the slash redirection.

## The expected behavior
- No redirection, use trailingSlash configuration (if true)
- encode correctly the query parameter

## Impacts ?
useLogin and ensureAuthorization functions use fetchAccessToken with the code argument.

## Potential work around
The code argument could be encoded before sending it to the function, inside the application code, but it won't remove the redirection.

Could be related to  #891  ???

**Comment by theodesp** [comment]
I'm closing this issue. You can follow the updates in: https://github.com/wpengine/faustjs/issues/1471
