### ISSUE TITLE
Cannot add Storybook to faustwp

### ISSUE THREAD

**Issue by Bowriverstudio** [wpengine/faustjs#1085]
Hello,

I am trying to get storybook / tailwind to run with the current faustwp  (0.1.1) - it does work with faustjs.

Storybook runs, but when it is installed something happens to faustwp and it doesn't run.

## Applicable Versions

-"dependencies": {
    "@apollo/client": "^3.6.6",
    "@faustwp/cli": "0.1.1",
    "@faustwp/core": "0.1.1",
    "@wordpress/base-styles": "^4.7.0",
    "@wordpress/block-library": "^7.13.0",
    "classnames": "^2.3.1",
    "next": "^12.1.6",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "sass": "^1.54.9"
  },
  "devDependencies": {
    "@babel/core": "^7.19.3",
    "@storybook/addon-actions": "^6.5.12",
    "@storybook/addon-essentials": "^6.5.12",
    "@storybook/addon-interactions": "^6.5.12",
    "@storybook/addon-links": "^6.5.12",
    "@storybook/builder-webpack5": "^6.5.12",
    "@storybook/manager-webpack5": "^6.5.12",
    "@storybook/react": "^6.5.12",
    "@storybook/testing-library": "^0.0.13",
    "autoprefixer": "^10.4.12",
    "babel-loader": "^8.2.5",
    "postcss": "^8.4.18",
    "tailwindcss": "^3.1.8"
  }

## Steps To Reproduce

Download repo 
https://github.com/Bowriverstudio/faustwp-storybook

npm i
npm run dev

**Comment by theodesp** [comment]
Hello @Bowriverstudio. Thank you very much for the feedback. 

I just verified the flow and I can see in my console that there is a missing dependancy for `graphql`
```
Error: Cannot find module 'graphql'
```
You will probably need to install it first to make it work:

```
npm i graphql
```

I will update the example getting started project to include this

**Comment by theodesp** [comment]
https://github.com/wpengine/faustjs/pull/1086

**Comment by Bowriverstudio** [comment]
@theodesp  

thank you
