### ISSUE TITLE
Bug: No terminal output received after legacy FaustJs upgrade

### ISSUE THREAD

**Issue by kmagee-reddoor** [wpengine/faustjs#1197]
During our upgrade from Legacy Faust to Latest Faust we've hit an issue where we cannot see build or dev errors in the command line. 

## Applicable Versions

- `@apollo/client` version: ^3.7.2
- `@faustwp/cli` version: ^0.1.5
- `@faustwp/core` version: ^0.1.3
- `graphql` version: ^16.6.0
- `next` version: 12.2.4
- `react` version: ^17.0.2
- `react-dom` version: ^17.0.2
- Windows version: 10
- Node version: 14.20.0

## Steps To Reproduce

1. Followed the migration steps outlined in [this documentation](https://faustjs.org/docs/migrationPath/overview)
2. Replaced Gqty with apollo
3. Replaced old faust with new packages mentioned in documentation
4. Wrote queries to take the place of Gqty methods
5. Generated `possibleTypes.json`
6. Made changes described [here](https://faustjs.org/docs/migrationPath/overview#changes-needed-during-migration-from-gqty-to-apollo)
7. Ran `$ yarn dev`
8. No output received,  command completes immediately

Link to code example:

This is a private repository. I'm posting the `package.json`, `next.config.js`, and `faust.config.js`.

File `~/pagkage.json`
```json
{
  "name": "someproject",
  "version": "1.0.2",
  "private": true,
  "scripts": {
    "dev": "faust dev",
    "build": "faust build",
    "start": "faust start",
    "lint": "faust lint",
    "snapshot": "percy snapshot ./tests/snapshots.js",
    "test": "start-server-and-test start http://localhost:3000 snapshot",
    "clean": "rimraf .next node_modules",
    "generate": "faust generatePossibleTypes",
    "wpe-build": "faust build",
    "format": "prettier --write 'src/**/*.{js,jsx,md,mdx,css,scss}'",
    "format:check": "prettier --check 'src/**/*.{js,jsx,md,mdx,css,scss}'",
    "css-lint": "stylelint \"**/*.{css,scss}\" --cache --cache-location .cache/.stylelintcache --rd"
  },
  "dependencies": {
    "@apollo/client": "^3.7.2",
    "@faustwp/cli": "^0.1.5",
    "@faustwp/core": "^0.1.3",
    "@popperjs/core": "^2.11.6",
    "bootstrap": "^5.2.1",
    "formik": "^2.2.9",
    "graphql": "^16.6.0",
    "next": "12.2.4",
    "react": "17.0.2",
    "react-bootstrap": "^2.5.0",
    "react-dom": "17.0.2",
    "react-icons": "^4.3.1",
    "react-swipeable": "^7.0.0",
    "react-text-mask": "^5.5.0",
    "react-waypoint": "^10.3.0",
    "sharp": "^0.30.5",
    "use-debounce": "^7.0.1",
    "uuid": "^9.0.0",
    "yup": "^0.32.11"
  },
  "devDependencies": {
    "@gqty/cli": "^3.1.0",
    "@percy/cli": "^1.16.0",
    "@wordpress/base-styles": "^4.1.1",
    "@wordpress/block-library": "^7.0.0",
    "dotenv-flow": "^3.2.0",
    "eslint": "8.9.0",
    "eslint-config-next": "12.0.10",
    "eslint-config-prettier": "^8.5.0",
    "eslint-plugin-import": "^2.25.4",
    "prettier": "^2.5.1",
    "rimraf": "^3.0.2",
    "sass": "^1.49.8",
    "start-server-and-test": "^1.15.2",
    "stylelint": "^14.11.0",
    "stylelint-config-twbs-bootstrap": "^6.0.0",
    "typescript": "^4.8.3"
  },
  "engines": {
    "node": ">=14.0.0",
    "npm": ">=1.22.0"
  },
  "browserslist": {
    "production": [
      ">0.5%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  }
}
```

File `~/next.config.js`
```javascript
const { withFaust, getWpHostname } = require('@faustwp/core');

/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  sassOptions: {
    includePaths: ['node_modules'],
  },
  eslint: {
    dirs: ['src'],
  },
  images: {
    domains: [getWpHostname()],
  },
  i18n: {
    locales: ['en'],
    defaultLocale: 'en',
  },
};

module.exports = withFaust(nextConfig);
```

File `~/src/faust.config.js`
```javascript
import { setConfig } from '@faustwp/core';

import templates from './wp-templates';
import possibleTypes from './possibleTypes.json';

/**
 * @type {import('@faustwp/core').FaustConfig}
 **/
export default setConfig({
  templates,
  experimentalPlugins: [],
  possibleTypes,
});

```

## The current behavior
The development server and runtime doesn't start up, see image.
![image](https://user-images.githubusercontent.com/94204629/210108629-fb4806c3-50b9-4db0-9d61-85f4b117aa6b.png)

## The expected behavior
The development server and runtime starts up or some error output is recieved

**Comment by theodesp** [comment]
Hey @kmagee-reddoor. 
The `faust` command is just a wrapper for `next` commands and there could be several reasons why a process does not start. But you can start checking those steps:

- Delete `node_modules` folder and run `yarn i ` again.
- Check if the `ignore-scripts` are set to true. See [SO question](https://stackoverflow.com/questions/59016328/npm-run-doesnt-do-anything).
- Use `--loglevel verbose` flag to see if something strange happening in the logs
- Try to run our example starter using the [QuickStart guide](https://faustjs.org/docs/getting-started#quick-start) to see if that works on your machine.

Let me know if you have recovered anything.

**Comment by kmagee-reddoor** [comment]
Thanks for the reply @theodesp , I have to move away from this issue for a few days but will be getting back into it ASAP later this week. Will let you know what I find.

**Comment by josephfusco** [comment]
Closing this ticket as a duplicate to #1144
