### ISSUE TITLE
Bug: Extra argument inside of renderMenu function of the example Next.js starter

### ISSUE THREAD

**Issue by Shaderpixel** [wpengine/faustjs#1235]
Within the Faust example Next.js starter, it appears that the NavigationMenu.js component's renderMenu function was called recursively with an extra boolean argument on [line 33](https://github.com/wpengine/faustjs/blob/main/examples/next/faustwp-getting-started/components/NavigationMenu/NavigationMenu.js#L33). This of course doesn't throw an error but is that intentional? If not intentional, I don't mind creating a PR to remove it.

**Comment by theodesp** [comment]
Hello @Shaderpixel. Thank you for reporting this. Sure feel free to submit a PR for this. There is a CLA you'll need to fill up as well. The steps are outlined here: https://github.com/wpengine/faustjs#contributor-license-agreement

**Comment by Shaderpixel** [comment]
Will do. Thanks and appreciate the guidance.

**Comment by blakewilson** [comment]
Thanks for the PR @Shaderpixel! Closing this now.
