### ISSUE TITLE
Please clearly describe your beta (non-production ready) status on your marketing site home page

### ISSUE THREAD

**Issue by felizuno** [wpengine/faustjs#1279]
We had a non-technical stakeholder ask us to use these tools and wasted cycles and money before somebody finally spoke up that they saw on your GitHub repo that the software is in beta. I find it extremely problematic to not mention this on your home page.

**Comment by ChrisWiegman** [comment]
The team is working towards a 1.0 version of Faust.js later this year. In the meantime we are proud of the fact that the product is running on numerous production sites for clients of all sizes today. That said, it is still a very new product, having just launched at the end of September so we will continue to version it < 1.0 until such a time where we have enough data to consider it at a 1.0 level. 

Today our website is to document what it can do and we are comfortable with how it presents the product, along with the GitHub readme, given that the version itself is still in the 0.2 range.

That said, I do understand your concern and we are ticketing a feature that would add the current version to the homepage of https://faustjs.org/.

**Comment by josephfusco** [comment]
https://github.com/wpengine/faustjs/pull/1333
