### ISSUE TITLE
Bug: Enabling "Post and Category URL rewrites" setting ignores protocol of configured front-end site URL

### ISSUE THREAD

**Issue by astratagem** [wpengine/faustjs#1302]
## Applicable Versions

- `@faustjs/core` version: n/a
- `@faustjs/react` version: n/a
- `@faustjs/next` version: n/a
- WordPress version: 6.1.1

Plugin version (relevant but not requested in issue template): 0.8.1 via `wpackagist-plugin/faustwp` in `composer.json`

## Steps To Reproduce

Given a local environment whose WordPress site URL begins with `https://` (e.g. via `mkcert`)
And a standard Next.js dev server on a non-SSL localhost port:

1. Set the "Front-end site URL" setting to match the Next.js dev server e.g. `http://localhost:3000`
2. Disable the "Post and Category URL rewrites" setting, save, flush rewrites
3. Observe that preview links begin with the correct `http://localhost:3000` base
4. Enable the "Post and Category URL rewrites" setting, save, flush rewrites
5. Observe that preview links are replaced with the incorrect `https://localhost:3000` base, which will not resolve

Link to code example: n/a

## The current behavior

The protocol of the "Front-end site URL" setting is disregarded in preview links

## The expected behavior

The protocol of the "Front-end site URL" setting is respected everywhere the value is used

**Comment by ChrisWiegman** [comment]
This should be addressed by #1290
