### ISSUE TITLE
Bug: wrong build of @faustwp/blocks published to npm 

### ISSUE THREAD

**Issue by szaleq** [wpengine/faustjs#1337]
## Applicable Versions

- `@faustjs/blocks` version: `0.1.1`

## Steps To Reproduce

1. Just install the package.

## The current behavior

Cannot import anything in TypeScript, because the package is missing a `cjs` build. 

![obraz](https://user-images.githubusercontent.com/25011639/226293139-4cc85d4d-c8c3-4960-8420-b5561099b79a.png)

The package only contains `dist/mjs` directory, while in `package.json` both `main` and `types` fields point to files inside `dist/cjs`.

![obraz](https://user-images.githubusercontent.com/25011639/226292511-34b32593-67d5-4d64-9260-f4ebbaee1c90.png)

![obraz](https://user-images.githubusercontent.com/25011639/226292562-b1b6f72d-ec53-447c-ae1a-44c3a2cbfa22.png)

## The expected behavior
I would expect to be able to use this module with TypeScript.

**Comment by blakewilson** [comment]
@theodesp Hmm. I think this is more than an invalid type. According to the screenshot, it looks like the `cjs` directory is not being built/bundled on the published NPM version.

**Comment by theodesp** [comment]
@blakewilson we do not use `cjs exports` on this one maybe it would be another ticket.
