### ISSUE TITLE
Bug: WordPressBlocksViewer TypeScript issues

### ISSUE THREAD

**Issue by szaleq** [wpengine/faustjs#1338]
## Applicable Versions

- `@faustqp/blocks` version: `0.1.1`
- WordPress version: `6.1.1`
- WPGraphQL version: `1.14.0`
- WPGraphQL Content Blocks version: `0.1.0`

## Steps To Reproduce

1. Install the WordPress plugins
2. Create a Faust/TypeScript project
3. Use [graphql-codegen](https://the-guild.dev/graphql/codegen) to generate TypeScript types from GraphQL schema exposed by WPGraphQL plugin (plus GraphQL document nodes from `.gql` query files)
4. Try to set up content blocks support as described in the documentation ([here](https://faustjs.org/docs/gutenberg/getting-started), and [here](https://faustjs.org/docs/reference/WordPressBlocksViewer))

Link to code example:
https://stackblitz.com/edit/nextjs-q4ei1g?file=src%2Fwp-templates%2Fpage%2Fpage.tsx

## The current behavior

It seems that the `@faustwp/blocks` doesn't work well with TypeScript.
The component types are invalid.
1. The component's return type is `JSX.Element[]` (an array of JSX elements) which is invalid. React component should return a single JSX element.
2. `contentBlocks` prop cannot accept an actual value returned from GraphQL. In GraphQL schema `contentBlocks` field is declared as an array containing block data or `null` values, which is not accepted here in the component.

The actual errors I'm talking about here are not visible in the code example, because the `@faustwp/blocks` package doesn't include a `cjs` build with types, which I mentioned [here](https://github.com/wpengine/faustjs/issues/1337).
Therefore, you can see this error:
![obraz](https://user-images.githubusercontent.com/25011639/226324205-4912c79b-b876-420a-83cd-b77ca63d39b4.png)
But in my local environment, I've applied a patch to `@faustwp/blocks` package and pointed to `mjs` types file instead, and then I get the errors with `WordPressBlocksViewer`.

![obraz](https://user-images.githubusercontent.com/25011639/226325012-c40ade94-6c4b-4085-8e19-87aa7c31ddea.png)
![obraz](https://user-images.githubusercontent.com/25011639/226325054-c7af02de-340e-4764-b951-dbcf199b8572.png)

## The expected behavior
`WordPressBlocksViewer` should be typed correctly, returning a single JSX element and accepting a value which comes from GraphQL as a prop. Otherwise, it's useless for TypeScript developers. 

Just for clarification: I didn't write any of the GraphQL types. All files with `.generated.ts` extension in the code example were generated with graphql-codegen based on the REAL SCHEMA exposed by the WordPress site with `WPGraphQL` and `WPGraphQL Content Blocks` plugins installed. It doesn't make any sense if I'm not able to use the result of GraphQL queries as a prop for this component. With the current type of `contentBlocks` prop I would need to manually loop over the result of a GraphQL `contentBlocks` field to filter out the possible `null` values.

**Comment by theodesp** [comment]
@szaleq I have a couple of PRs fixing all observed issues with TS. Thanks for the feedback!
