### ISSUE TITLE
Some TypeScript types are useless.

### ISSUE THREAD

**Issue by szaleq** [wpengine/faustjs#1339]
There are particularly two types I'm talking about:
## 1. `WordPressTemplate` from `@faustwp/core`
This type defines a React Functional Component with additional properties (`query` and `variables`) but is useless for developers.
First of all, it should be exported from the root types file (it needs to be imported from `@faustwp/core/dist/cjs/getWordPressProps` at the moment).
Secondly, there is no practical use case for this type because it doesn't allow to specify prop types for the component.
[Here](https://stackblitz.com/edit/nextjs-q4ei1g?file=src/wp-templates/page/page.tsx) you can see a `TemplateComponent` interface which I've created to replace `WordPressTemplate` type for now in my pages. It accepts data type as param and defines a Functional Component with `FaustTemplateProps<Data>`, This way I can simply pass the type generated from my GraphQL query as a param and have a nicely typed props inside my template component: 
![obraz](https://user-images.githubusercontent.com/25011639/226328899-4e4a4630-1dfe-4ee7-97ff-cad52f9fbbd8.png)

Please consider changing `WordPressTemplate` type to accept data type as param and export it from the root types file.

## 2. `WordPressBlock` from `@faustwp/blocks`
The same case: `WordPressBlock` is defined as a Functional Component with some additional properties (`name`, `displayName`, `config`) but the type doesn't allow to specify props. 
[Here](https://stackblitz.com/edit/nextjs-q4ei1g?file=src/wp-blocks/CoreParagraph/CoreParagraph.tsx) there is my version of the `WordPressBlock` type which simply accepts props type as a param. This way I can just pass the generated types for the GraphQL fragment defined for this block as a type param and have a typed props inside the component:
![obraz](https://user-images.githubusercontent.com/25011639/226329548-ba8850a0-726b-44b4-8a49-7a106929d7ca.png)
![obraz](https://user-images.githubusercontent.com/25011639/226329589-c74d3b68-68e2-4d11-a837-48a0bb687ffe.png)
![obraz](https://user-images.githubusercontent.com/25011639/226329792-e13d84c8-eb0f-4809-a895-50b752b88d62.png)
![obraz](https://user-images.githubusercontent.com/25011639/226329830-ceee5026-a964-4506-bba2-b07272cde009.png)

Please consider making the types more useful.

**Comment by theodesp** [comment]
Hey @szaleq Thank you for the feedback. You are right some of the types are not up to scratch with TS. I will create a PR that will provide those types instead:

```
export declare type WordPressBlockBase = React.FC & {
    displayName: string;
    name: string;
    config: {
        name: string;
    };
};
export type WordPressBlock<P = {}> = FC<P> &
  Partial<Pick<WordPressBlockBase, 'config' | 'displayName' | 'name'>>;
```
I'm adding a Partial here as you may not need to declare all properties in advance.

**Comment by theodesp** [comment]
Also it looks like there is a confusion between `WordPressTemplate` inside `@faustwp/core/dist/cjs/getWordPressProps` and `WordPressTemplate` inside `@faustwp/core/dist/cjs/components/WordPressTemplate.tsx`. The first one is a type and the second one is a React Component. I need to differentiate those two.

Somethig like:

```
export interface FaustTemplate<Data> extends FC<FaustTemplateProps<Data>> {
  query?: WordPressTemplate['query'];
  variables?: WordPressTemplate['variables'];
}
```

**Comment by szaleq** [comment]
Thanks @theodesp for looking into this.
Instead of using Partial type you could just make the props optional.
```
export declare type WordPressBlockBase = React.FC & { 
    displayName?: string;
    name?: string;
    config?: {
        name: string;
    };
};

export type WordPressBlock<P = {}> = FC<P> & Pick<WordPressBlockBase, 'config' | 'displayName' | 'name'>;
```
