### ISSUE TITLE
Bug: Invalid return type of getWordPress props function

### ISSUE THREAD

**Issue by szaleq** [wpengine/faustjs#1340]
The return type doesn't match the return types defined in Next. 

## Applicable Versions

- `@faustwp/core` version: `0.2.6`

## Steps To Reproduce

1. Try to use result of `getWordPressProps` as a return value for `getStaticProps` or `getServerSideProps`

## The current behavior

Here is the `GetStaticPropsResult` type from Next:
![obraz](https://user-images.githubusercontent.com/25011639/226594685-9ae33350-7e6e-42b2-b744-0f68fbdfa455.png)

And here is `GetServerSidePropsResult` from next:
![obraz](https://user-images.githubusercontent.com/25011639/226594762-29fb4d3d-8adf-4727-952d-0ab0fba004fc.png)

In both cases `notFound` can only have a type `true`, which makes sense, because it's used in a union type. So it's either you return object with `props` OR object with `redirect` OR object with `notFound: true`. You can't return something like `{ notFound: false }` because it won't make any sense. 

Here is the TypeScript declaration of `getWordPressProps` function from Faust:
![obraz](https://user-images.githubusercontent.com/25011639/226595245-88146352-969d-4f0e-b2f3-42768722338e.png)

It's typed as it could return precisely this: `{ notFound: false }` which causes the TypeScript error.

Code example:
https://stackblitz.com/edit/nextjs-q4ei1g?file=src/pages/[...pageUri].tsx

![obraz](https://user-images.githubusercontent.com/25011639/226596086-6f7e32b7-d0cb-4f4b-8edc-077ce6180926.png)

## The expected behavior

The return type of `getWordPressProps` should match the return types of `getStaticProps` and `getServerSideProps`.

**Comment by theodesp** [comment]
Hey @szaleq thanks for raising this up. Apparently the type signature for the `GetStaticPropsResult` and `GetServerSidePropsResult` uses a narrower value for `notFound: true`

```
export type GetServerSidePropsResult<P> =
  | { props: P | Promise<P> }
  | { redirect: Redirect }
  | { notFound: true }

export type GetStaticPropsResult<P> =
  | { props: P; revalidate?: number | boolean }
  | { redirect: Redirect; revalidate?: number | boolean }
  | { notFound: true; revalidate?: number | boolean }
  ```

So basically we will have to change the return type to match this type: 
```
export declare function getWordPressProps(options: GetWordPressPropsConfig): Promise<{
    props: {
        [key: string]: any;
    };
    revalidate?: number | boolean | undefined;
} | {
    notFound: true;
}>;
```

**Comment by theodesp** [comment]
@szaleq I've merged the issue. It will be visible in the next release.
