### ISSUE TITLE
Use `index.php?graphql` for GraphQL endpoint

### ISSUE THREAD

**Issue by justlevine** [wpengine/faustjs#1360]
In order to support custom graphql endpoints (and _maybe_ sites without pretty permalinks) we should use the underlying WP query to get the GraphQL endpoint in `generatePossibleTypes` and `getGraphqlEndpoint` (i.e `/index.php?graphql` instead of `/graphql`).

While this is technically filterable in the app itself with `graphqlEndpoint`, that filter has no effect on type generation. Also, this approach negates the need for a filter entirely (unless maybe you're mocking endpoint data? is that a thing in the frontend ecosystem?).

**Comment by josephfusco** [comment]
Related: https://github.com/wpengine/faustjs/pull/1318

**Comment by josephfusco** [comment]
Closed by https://github.com/wpengine/faustjs/pull/1318. Thanks @justlevine!
