### ISSUE TITLE
Bug: Draft Previews won't work when next.config 'trailingSlash' is turned on

### ISSUE THREAD

**Issue by CesarBenavides777** [wpengine/faustjs#1393]
## Applicable Versions

- `@faustwp/core` version: "0.2.11"
- `@faustwp/cli` version: "0.2.10"
- WordPress version: 6.1

## Steps To Reproduce

1. Turn on trailingSlash in next.config.js
2. Try and preview a draft post
3. It redirects you to the homepage usually with no preview content

Link to code example:
https://github.com/NoisyTrumpet/gods-dogs/blob/error-reproduction/next.config.js#L8

## The current behavior
Trailing Slash breaks draft previews

## The expected behavior
Draft Previews work with trailingSlash: true

## Workaround
Set `trailingSlash: false` in next.config file

**Comment by theodesp** [comment]
Hey @CesarBenavides777.

I'm unable to reproduce using the https://github.com/wpengine/faust-scaffold-ts and a new Local install.

Is there any other info into the console or the next.js server that my help debug this by exposing the `FAUST_DEBUG=true`env variable?

Could you also try to remove the following import from the api config?
https://github.com/NoisyTrumpet/gods-dogs/blob/d74884f031acf21a63d99f119776c7742227de86/pages/api/faust/%5B%5B...route%5D%5D.ts#L1
```
//import "../../../faust.config";
```

**Comment by theodesp** [comment]
Closing this one due to inactivity. If you experience the issue feel free to re-submit.
