### ISSUE TITLE
Bug: Faust.js i18n Legacy Version

### ISSUE THREAD

**Issue by MozerBuce** [wpengine/faustjs#1422]
Hi everyone!

i am currently working on a project using the legacy version and i need to make it multilingual, i followed this [blog post](https://dev.to/franadev/multi-lingual-headless-wordpress-1l71) or [here](https://wpengine.com/builders/multilingual-headlesswordpress-with-nextjs-wpgraphql-polylang)  to setup the wordpress but he uses pure next.js on the frontend,

So i am facing problems with how to put the where clause on faust.js so that it can work, any guide? help?

Thanks in advance.

**Comment by theodesp** [comment]
Hey @MozerBuce. Let's not paint this as a bug since there is nothing to fix or out of the ordinary.  Since we have the discussion thread here https://github.com/wpengine/faustjs/discussions/1421 I will have to close this issue and follow up there.
