### ISSUE TITLE
Bug: Changed getStaticProps to getServerSideProps, clicking the link resulted in a 404 error. 

### ISSUE THREAD

**Issue by youdianfan** [wpengine/faustjs#1423]
Using the official demo repository code, I modified the getStaticProps in pages/index.js and pages/[...wordpressNode].js to getServerSideProps. Then I added a Link for navigation in the wp-templates/front-page.js file, but it resulted in a 404 error when navigating to the linked page.

## Applicable Versions
```
{
    "@apollo/client": "^3.6.6",
    "@faustwp/cli": "0.2.12",
    "@faustwp/core": "0.2.11",
    "@wordpress/base-styles": "^4.7.0",
    "@wordpress/block-library": "^7.13.0",
    "classnames": "^2.3.1",
    "graphql": "^16.6.0",
    "next": "^12.1.6",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "sass": "^1.54.9"
  }
```
- WordPress version: 6.2

## Steps To Reproduce

![image](https://github.com/wpengine/faustjs/assets/27018910/c9a52c24-792e-462f-8df2-d5ec9044d11e)
![image](https://github.com/wpengine/faustjs/assets/27018910/127699db-a6b2-4d84-8a44-b2094bd2fbc2)
![image](https://github.com/wpengine/faustjs/assets/27018910/17ebdb56-101a-4350-af9b-24bddc22d7a0)
![image](https://github.com/wpengine/faustjs/assets/27018910/3daec255-4d14-4a7b-b640-28977c238575)

Link to code example:

## The current behavior
404 error

## The expected behavior
normal display

**Comment by theodesp** [comment]
Hey @youdianfan . I tried to replicate with a new site and using `getServerSideProps` with a link to an existing page but I havent' been able to verify that it shows 404. The navigation works as expected. Are you running a production build?

**Comment by theodesp** [comment]
Actually @youdianfan  I was able to verify. It seems we are missing a commit in the latest release tha fixes this one We will push an update on monday.

**Comment by theodesp** [comment]
This was already [fixed here](https://github.com/wpengine/faustjs/commit/0521fd336400f8b633e645b7ed18a86194deedcb).

**Comment by theodesp** [comment]
will close

**Comment by youdianfan** [comment]
Thank you very much for your reply, after installation, to solve this problem.
