### ISSUE TITLE
Bug: Issue with Upgrading to Next.js 13 and Compatibility with @faustjs Packages

### ISSUE THREAD

**Issue by avivdaniel** [wpengine/faustjs#1435]
## Applicable Versions

- `@faustjs/core` version: none
- `@faustjs/react` version: none
- `@faustjs/next` version: none
Im using:
"next": "^12.1.0",
"react": "17.0.2",

## Steps To Reproduce

1.
2.

Link to code example:

## The expected behavior

Dear @faustjs Maintainers,

I hope this message finds you well. I'm currently facing an issue with upgrading my application to Next.js 13 and ensuring compatibility with the @faustjs packages.

I noticed that the @wpengine/headless package, which I have been using, is deprecated and recommends using @faustjs/core, @faustjs/react, and @faustjs/next instead. However, I'm uncertain about the necessary steps and requirements for completing the upgrade successfully.

When attempting to upgrade using the command npm install next@latest react@latest react-dom@latest, I encountered the following error:
`npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: next@12.1.6
npm ERR! node_modules/next
npm ERR!   peer next@">=10.0" from @wpengine/headless@0.6.3
npm ERR!   node_modules/@wpengine/headless
npm ERR!     @wpengine/headless@"^0.6.3" from the root project
npm ERR!   next@"13.4.4" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! next@"13.4.4" from the root project
npm ERR!
npm ERR! Conflicting peer dependency: react@18.2.0
npm ERR! node_modules/react
npm ERR!   peer react@"^18.2.0" from next@13.4.4
npm ERR!   node_modules/next
npm ERR!     next@"13.4.4" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
`
Before proceeding with the upgrade, I would like to clarify the following:
1. Compatibility: Can I upgrade my application to Next.js 13 **without removing** the "@wpengine/headless" package? If so, are the @faustjs packages (@faustjs/core, @faustjs/react, and @faustjs/next) fully compatible with Next.js 13 and React 18?
2. Upgrade Steps: Could you please provide me with the necessary steps to successfully upgrade my application from Next.js 12 to Next.js 13 while ensuring compatibility with the "@wpengine/headless" package?

Thank you for your assistance in resolving this issue.

Best regards,
Aviv.

**Comment by avivdaniel** [comment]
> Hey @avivdaniel. Thanks for the report. I don't think there is a problem using the latest Next.js 13 package along with `@wpengine/headless` package. I just tried to install it using this repo here: https://github.com/wpengine/faust-scaffold-ts and I didn't encounter any issues here when installing.
> 
> I think what you need to do is maybe try to remove the `@wpengine/headless` package:
> 
> ```shell
> npm uninstall @wpengine/headless
> ```
> 
> ![](chrome-extension://annlhfjgbkfmbbejkbdpgbmpbcjnehbb/images/saveicon.png) Save
> Then install the next.js 13:
> 
> ```shell
> npm install next@latest react@latest react-dom@latest
> ```
> 
> ![](chrome-extension://annlhfjgbkfmbbejkbdpgbmpbcjnehbb/images/saveicon.png) Save
> And then reinstall `@wpengine/headless package` again:
> 
> ```shell
> npm i @wpengine/headless
> ```
> 
> ![](chrome-extension://annlhfjgbkfmbbejkbdpgbmpbcjnehbb/images/saveicon.png) Save
> You can also try to use the `--force` option if that doesn't work:
> 
> ```shell
> npm install next@latest react@latest react-dom@latest --force
> ```
> 
> ![](chrome-extension://annlhfjgbkfmbbejkbdpgbmpbcjnehbb/images/saveicon.png) Save
> However you will need to do a smoke test that the site runs successfully since the `@wpengine/headless` package hasn't been updated for at least 3 years and we don't maintain testing infrastructure for this version.

Works for me! thanks!

**Comment by tuanfront-end** [comment]
> Hey @avivdaniel. Thanks for the report. I don't think there is a problem using the latest Next.js 13 package along with `@wpengine/headless` package. I just tried to install it using this repo here: https://github.com/wpengine/faust-scaffold-ts and I didn't encounter any issues here when installing.
> 
> I think what you need to do is maybe try to remove the `@wpengine/headless` package:
> 
> ```shell
> npm uninstall @wpengine/headless
> ```
> 
> Then install the next.js 13:
> 
> ```shell
> npm install next@latest react@latest react-dom@latest
> ```
> 
> And then reinstall `@wpengine/headless package` again:
> 
> ```shell
> npm i @wpengine/headless
> ```
> 
> You can also try to use the `--force` option if that doesn't work:
> 
> ```shell
> npm install next@latest react@latest react-dom@latest --force
> ```
> 
> However you will need to do a smoke test that the site runs successfully since the `@wpengine/headless` package hasn't been updated for at least 3 years and we don't maintain testing infrastructure for this version.

Hi, thank you, but can you please check thís issue please - https://github.com/wpengine/faust-scaffold-ts/issues/10
