### ISSUE TITLE
Bug: "data.viewer is null" on page load

### ISSUE THREAD

**Issue by rshov** [wpengine/faustjs#1443]
Hello, I am intermittently getting an error on page refresh when developing locally against my local WordPress install (using the Local app). It does not happen consistently, just seemingly randomly after page refresh.

![image](https://github.com/wpengine/faustjs/assets/10855603/ed6cbc42-ee49-4f2a-8baa-83eec642acc0)

If I refresh the page again after getting this error, it will usually load correctly, but sometimes I will get the error again.

The highlighted line below appears to be what this error is referring to. Is it possible for data.viewer to be null sometimes? If so, should this line be changed to `if (!data.viewer?.shouldShowFaustToolbar) {`

![image](https://github.com/wpengine/faustjs/assets/10855603/115d7aca-0653-460c-a706-8fb165a090cb)

## Applicable Versions

- `@faustjs/core` version: 0.2.13
- `@faustjs/react` version: React version is 18.2.0, but I also saw the same error on version 17.0.2.
- `@faustjs/next` version: Next.js version is 12.1.6
- WordPress version: 6.2.2

## Steps To Reproduce

1. Start the server locally using `npm run dev`
2. Refresh the page in my faust.js app and sometimes will see the error, other times the page will load correctly.
3. When the error happens, the page appears to start loading but then the runtime error is shown.

Link to code example:

I will create a code example if needed. I wanted to get feedback on the possible code fix above before taking the time to create a runnable example.

## The current behavior

Sometimes see the error above.

## The expected behavior

Expect the page to load correctly without errors.

**Comment by theodesp** [comment]
Hello @rshov. Thanks for the report. What is your faust.config.js look like? are you using the `experimentalToolbar`?
Also which version of the FaustWP plugin and WPGraphQL are you using?

**Comment by theodesp** [comment]
`data?.viewer` is null because the request is not authenticated. The `isAuthenticated` will be false if that is the case. 
If you current user is not authenticated the in the first render pass the `data?.viewer=null`. However if the client passes the correct auth cookie then `isAuthenticated` will be true and `data?.viewer` will resolve the data.

Not sure why it stays null though if you are authenticated. I will open a ticket since I was able to verify the issue with the code you posted:

<img width="1444" alt="Screenshot 2023-06-06 at 15 29 59" src="https://github.com/wpengine/faustjs/assets/328805/a25d8157-a01e-4701-9315-2d06b02957bf">

**Comment by theodesp** [comment]
@rshov After some quick debugging I found to be a quirky race condition when you call this useQuery hook.

The thing is that the first time the call is not authenticated so it does not have the Bearer token in the request:

```
curl 'http://mysite.local/index.php?graphql' \
  -H 'Accept-Language: en-GB,en;q=0.9,de;q=0.8,el;q=0.7,en-US;q=0.6' \
  -H 'Cache-Control: no-cache' \
  -H 'Connection: keep-alive' \
  -H 'DNT: 1' \
  -H 'Origin: http://localhost:3000' \
  -H 'Pragma: no-cache' \
  -H 'Referer: http://localhost:3000/' \
  -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36' \
  -H 'accept: */*' \
  -H 'authorization;' \
  -H 'content-type: application/json' \
  --data-raw '{"variables":{},"query":"{\n  viewer {\n    id\n    databaseId\n    firstName\n    lastName\n    email\n    capabilities\n    shouldShowFaustToolbar\n    __typename\n  }\n}"}' \
  --compressed \
  --insecure
  ```
  
  
I found that if you use the skip parameter you no longer have this issue:

```
const { data, loading } = useQuery(
    gql`
      {
        viewer {
          id
          databaseId
          firstName
          lastName
          email
          capabilities
          shouldShowFaustToolbar
        }
      }
    `,
    { client, skip: !isAuthenticated },
  )
 ```
Let me know if that fixes your issue.

**Comment by rshov** [comment]
That did it! Just passing `skip: !isAuthenticated`. Thank you so much for your quick response and fix!
