### ISSUE TITLE
Bug: Data not updating on page/route change when click on link

### ISSUE THREAD

**Issue by Muzammil-khan710** [wpengine/faustjs#1446]
When we try to open a blog-page using links on the same page, the route changes but the data remains same and when we refresh the data changes . `There are no console errors.`

## Applicable Versions

- `@faustwp/core` version: 0.2.11
- `react` version: 18.2.0
- `nextjs` version: 13.1.5
- WordPress version: 6.2.2

## Steps To Reproduce

1. Visit the page  .
2. Now scroll to `Other Related Articles` section .
3. Click on any of the `first two links` .
4. Now after clicking your` route/path` is changed but data remains the same .
5. But if you` reload `the page you will see new(updated) data.

Link to code example:
here is the live link ->  https://rovae-website-fr5fc4tcn-chintankamani.vercel.app/blog/the-importance-of-user-centered-design

## The current behavior
Right now on clicking link the route of page is changing but it is showing old data and if we refresh it shows new data .

## The expected behavior
When we click on link It should update the data without refreshing the page.

**Comment by Muzammil-khan710** [comment]
Hey. @theodesp  I have resolved 500 server issue issue. 
Query 

SingleBlog.variables = ({ uri }: any) => {
  return { uri };
};


```
SingleBlog.query = gql`
${components.CoreParagraph.fragments.entry}
${components.CoreHeading.fragments.entry}
${components.CoreImage.fragments.entry}
query MQ($uri: ID = "") {
    blogs {
      edges {
        node {
          title
          date
          excerpt
          uri
          featuredImage {
            node {
              sourceUrl
              title
            }
          }
        }
      }
    }
    blog(id: $uri, idType: URI) {
      title
      id
      date
      excerpt
      seo {
        title
        metaDesc
        opengraphImage {
          mediaItemUrl
        }
        schema {
          raw
        }
      }
      featuredImage {
        node {
          sourceUrl
          title
        }
      }
      author {
        node {
          name
        }
      }
      categories {
        edges {
          node {
            name
          }
        }
      }
      editorBlocks {
        renderedHtml
        __typename
        clientId
        name
        ...${components.CoreParagraph.fragments.key}
        ...${components.CoreHeading.fragments.key}
        ...${components.CoreImage.fragments.key}
      }
    }
  }
`
```

**Comment by theodesp** [comment]
Hey @Muzammil-khan710 thanks. I suspect a caching issue.

Are you aware of this?
https://github.com/vercel/next.js/discussions/22512

**Comment by Muzammil-khan710** [comment]
Yes @theodesp tried it. But the issue persist.
