### ISSUE TITLE
Bug: Internal Server Error 500 when authenticating with app deployed to Vercel (sometimes)

### ISSUE THREAD

**Issue by rshov** [wpengine/faustjs#1471]
I often get an internal server error 500 when authenticating through Faust redirect authentication for our app deployed on Vercel. The error occurs roughly 9 out of 10 times, but then it occasionally authenticates correctly and everything works once it does.

The Faust app is deployed on Vercel using Node.js v16.x, and the environment variables are set correctly for FAUST_SECRET_KEY and NEXT_PUBLIC_WORDPRESS_URL.

The strange part is that I only see this problem when using the *deployed* app. I can point my localhost faust app to the same WordPress site and it works perfectly.

I think this could be related to this issue: https://github.com/wpengine/faustjs/issues/815#issuecomment-1076894178

There is a pull request (https://github.com/wpengine/faustjs/pull/818) that he says fixed his issue, but it looks like the change does not exist in the code today: https://github.com/wpengine/faustjs/blob/bf3e3be37b658280be30a51db5396d99eead8ab5/packages/core/src/auth/client/accessToken.ts#L143C28-L143C28

## Applicable Versions

- `@faustjs/core` version: 1.0.1
- `@faustjs/react` version: 18.2.0
- `@faustjs/next` version: 12.3.4
- WordPress version: 6.2.2

## Steps To Reproduce

1. Create a faust app using the Quick Start documentation. 
2. Create a page in the app that uses the useAuth() with redirect based authentication.
3. Test that this app can authenticate correctly on a localhost app.
4. Deploy the app to Vercel and now the authentication will often result in an Internal Server Error 500.

![image](https://github.com/wpengine/faustjs/assets/10855603/8afe750f-a213-4d4e-8d80-494fcb7e04cb)

Link to code example:

I can create a runnable code sample if needed. I am just using the useAuth() hook from @faustwp/core in a Next.js page to login and check that the user is authenticated. I am not using any of the other Faust features.

## The current behavior

I receive an Internal Server Error 500 most of the time when using redirect based authentication with Faust, when app is deployed on Vercel.

## The expected behavior

Expect the redirect based authentication to work correctly whether on localhost or Vercel. It would be nice to see if the pull request referenced above from a year ago fixes the problem.

**Comment by ChrisWiegman** [comment]
Thank you, @rshov. As this is a Vercel issue and not normally the platform our team develops on I do not have an immediate solution for you however I have ticketed the issue on our internal system for a much deeper investigation as soon as we can get to it.

**Comment by theodesp** [comment]
Hey @rshov. Could you provide us with a copy of the request and response of the 500 error? You can do that via the Network tab in Chrome, right click and select **Copy Response**

<img width="973" alt="Screenshot 2023-06-26 at 12 13 06" src="https://github.com/wpengine/faustjs/assets/328805/5e50042b-e0b1-4660-ac50-1a4ad362131d">

**Comment by rshov** [comment]
@theodesp sure, the response is below. Let me know if I can provide anything else. Thank you!

`{"code":"invalid_request","message":"Invalid authorization code or refresh token.","data":null}`

![image](https://github.com/wpengine/faustjs/assets/10855603/24d70861-bb85-494f-97ea-d9ada0dff46d)

**Comment by theodesp** [comment]
@rshov Thanks it looks like it's related to https://github.com/wpengine/faustjs/issues/815#issuecomment-1076894178
