### ISSUE TITLE
Bug:  Preview Mode not working in Nextjs

### ISSUE THREAD

**Issue by Muzammil-khan710** [wpengine/faustjs#1473]
I have followed this [guide](https://faustjs.org/docs/next/guides/post-page-previews) . But  I realized that the "preview" mode feature in the WordPress dashboard is not working as expected . I am also using `custom-post-type` named as `articles` and  which gets resolve in single-article inside wp-templates. But when I am trying to preview my article (from wordpress) it is showing blank screen and it is getting resolved in `single-article` template. I am just receiving this inside console of `preview.tsx` page  `{className: 'jsx-3925027921 ' }` . 

## Applicable Versions

- WordPress version: 6.2.2
- Wpgraphql version: 1.14.4
- WPGraphQL Content Blocks version: 0.3.0
- Genesis Custom Blocks version: 1.5.1
- NextJs version: 13.1.5 
- React version: 18.2.0
- apollo/client version: 3.7.14 
- faustwp/blocks version: 0.3.1
- faustwp/cli : 0.2.12
- faustwp/core: 0.2.11

## The current behavior
It is not showing any content in preview mode.

## The expected behavior
It should show the content in  preview mode

**Comment by mindctrl** [comment]
@Muzammil-khan710 can you try upgrading to the latest versions of all the Faust  packages? We fixed post previews in #1438 and released it in 1.0.0.

**Comment by Muzammil-khan710** [comment]
@mindctrl  I have updated packages but still same issue.

**Comment by theodesp** [comment]
Hey @Muzammil-khan710 is it possible to provide us with a small minimal reproduction example repo? We are not experiencing any issues with previews in our part.

Just provide only the Next.js part and we will create a new install with the provided plugins and try to verify.

**Comment by Muzammil-khan710** [comment]
Hey @theodesp , here is minimal example [repo]( https://github.com/Muzammil-khan710/nextjs-wordpress)

**Comment by Muzammil-khan710** [comment]
Hey @theodesp, I looked and implemented changes as mentioned above and now previews  for pages  are working as expected. Thanks for your help.
