### ISSUE TITLE
Previewing only works for WP post links from site root, not from custom paths

### ISSUE THREAD

**Issue by wjohnsto** [wpengine/faustjs#149]
Previews will only work if your post links are from the root of your site (e.g. `mysite.local/hello-world`) rather than at a separate path (e.g. `mysite.local/blog/hello-world`). 

I believe this is an issue with the plugin. The plugin is aware of and creates direct URLs to where it assumes the frontend has the preview handler API router. So if your "Front-end site URL" in your headless settings is `https://mysite.local/blog` then the plugin will end up sending you to `https://mysite.local/blog/api/auth/wpe-headless?redirect_url=blog%2Fhello-world%2Fpreview%2F21` if you are trying to preview an autosave, and `https://mysite.local/blog/api/auth/wpe-headless?redirect_url=draft%2Fpreview%2F21` if you are trying to preview a draft post. There are a few things wrong with this,:

1. The frontend site doesn't have its API route at `/blog/api/...`. In fact, in its current state the frontend is not able to specify a custom API route for the preview handler.
    - You can kind of get around this by specifying the following in your `next.config.js`
    ```js
    rewrites() {
      return [
        {
          source: '/blog/api/:path*',
          destination: '/api/:path*',
        },
      ];
    },
    ```
    - While the code above works to rewrite the API route, it's a hack and should not be relied on
1. Notice that for draft posts the redirect URL is `draft/preview/21`. This won't work, as the URL would need to be `blog/draft/preview/21`.

There are a couple ways you could deal with this issue, but before I get into that it is important to understand the reason the WP plugin is currently using direct URLs to the API route in the first place rather than rewriting to be the same URL WP would use. When using a WP site to preview drafts/autosaves the URL will contain preview information in the query string. In a Next app, you do not have access to query parameters in the `GetStaticPropsContext` (see an issue about it [here](https://github.com/vercel/next.js/discussions/17269)). So in order to support previewing with Next and `getStaticProps` it is necessary to rewrite the URL query parameters to be part of the path.

With that being said, I think some day in the future Next may support query params in `GetStaticPropsContext` and when that day comes we should revert back to simply using the same WP frontend URLs for previewing, which would in-effect decouple the plugin from the framework. For now, we have to come up with some way to do it that supports custom frontend routes for blog posts. Here is my suggestion:

1. We refactor the plugin to have 2 URL options
    - The first one is the root URL (e.g. `https://mysite.local/`)
    - The second one is the root list posts path (e.g. `/blog/`), which defaults to `/`
2. When you are in `wp-admin` and want to preview a post, the URL will be rewritten to use the same schema that WP uses, only we will append `/preview/` to the front of the path (e.g. `https://mysite.local/preview/?p=21&preview=true` or `https://mysite.local/preview/hello-world/?preview_id=1&preview_nonce=ac879988a0&preview=true`).
3. On the frontend/framework side, we instruct people to create a specific `/pages/preview/[[...page]].tsx` that will serve as their page for previews.
    - This page could be fully client-side rendered or could use `getServerSideProps`, but shouldn't use `getStaticProps`
4. Logic is added to the framework to handle redirecting for authentication based on frontend configuration only. This effectively prevents the WP plugin from having to know/direct anything about the frontend routes except for the configured preview route.

I think doing this or something similar makes the most sense for now and will decouple the plugin from the frontend as much as possible while we wait for Next to add support for query params in `GetStaticPropsContext`.

Thoughts?

**Comment by nickcernis** [comment]
Thanks for the write-up, Will.

The proposal looks good to enable previews under subdirectories and decouple the plugin some more.

We just need to be precise with the labelling of any second URL fields we introduce, so that it's completely clear why it exists and and why someone might need to adjust it.

(I also up-voted https://github.com/vercel/next.js/discussions/17269.)
