### ISSUE TITLE
Bug: Gutenberg Preview crashes 

### ISSUE THREAD

**Issue by Julhol-droid** [wpengine/faustjs#1491]
When clicking multiple times on the "Preview in new tab" button in Gutenberg Editor the browser crashes.
I already tried updating to FaustWP version 1.0.0 but this didn't fix it. When the plugin is deactivated it works just fine.

![image](https://github.com/wpengine/faustjs/assets/79325648/b703b4be-d229-4050-8451-3424d0194f8c)

## Applicable Versions

- FaustWP Plugin version: 0.8.1
- WordPress version: 6.0.1

## Steps To Reproduce

1. Make or edit a new page
2. Click on the "Preview in new tab" button
3. Once the new tab opens get back to the editor and click the button again
4. Repeat step 2 approximately 10 - 15 times
5. At some time the browser window will not response anymore. If you wait sometime it response again

## The current behavior

Browser doesnt response after multiple clicks on "Preview in new tab" button

## The expected behavior

There shouldn't be a response bug

Thank you in advance!

**Comment by theodesp** [comment]
Hey @Julhol-droid . Which browser are you using and which version?

**Comment by Julhol-droid** [comment]
> Hey @Julhol-droid . Which browser are you using and which version?

Chrome Version 114.0.5735.199

**Comment by theodesp** [comment]
The fix should be available in the canary releases.
