### ISSUE TITLE
Bug: "Edit Post" node in the toolbar not working when previewing posts

### ISSUE THREAD

**Issue by renatonascalves** [wpengine/faustjs#1515]
## Applicable Versions

- `@faustjs/core` version: 1.0.3
- `@faustjs/react` version: Not used.
- `@faustjs/next` version: Not used.
- WordPress version: 6.2.2

I followed this "Get started with Faust" guide: https://faustjs.org/tutorial/get-started-with-faust

## Steps To Reproduce

https://github.com/wpengine/faustjs/assets/19148962/8e6e4539-4688-4c15-9765-1397322d6bde

Link to code example:

See this Github issue for a technical overview of the problem: https://github.com/wp-graphql/wp-graphql/issues/2876

## The expected behavior

I expected the "Edit Post" toolbar node to be available when previewing posts and the link should point me to the edit post screen of the post I'm previewing it.

**Comment by renatonascalves** [comment]
There is one way Faust could handle this in the meantime. Getting the id in the params and swap for the one in the response. In that way, the edit post toolbar node would be available.

**Comment by mindctrl** [comment]
@renatonascalves thank you for the report! Added to our backlog and we'll take a look at this as soon as possible.

**Comment by mindctrl** [comment]
PR in progress here: https://github.com/wpengine/faustjs/pull/1556
