### ISSUE TITLE
Bug: Preview link missing `p` and `previewPathName` after saving draft

### ISSUE THREAD

**Issue by stephanonline** [wpengine/faustjs#1561]
The preview link is no longer working when you save the draft explicitly.

## Applicable Versions

- WordPress plugin version: 1.0.3
- WordPress version: 6.3

## Steps To Reproduce

1. Create a new page
2. Click on "Save draft"
3. Click on "Preview" => "Preview in new tab"

## The current behavior

Preview link does not contain the faustwp parameters required by the frontend

## The expected behavior

Preview link is the the `window._faustwp_preview_link._preview_link` found in https://github.com/wpengine/faustjs/blob/canary/plugins/faustwp/includes/replacement/previewlinks.js#L8

**Comment by mindctrl** [comment]
@stephanonline thank you for the report and apologies for the inconvenience. We're going to prioritize this issue and fix it as soon as possible. We'll update you here when we have more info.

**Comment by JEverhart383** [comment]
Ahh, interesting, I'm sure you already got here, but it looks like the menu rerenders after the first click and does not make the clones. A workaround in the meantime should be refreshing the page, which should run the preview link replacement script again. Any other action in the editor, like saving again or clicking the preview link seems to re-add the default preview link
![Screenshot 2023-09-06 at 9 51 24 AM](https://github.com/wpengine/faustjs/assets/7818951/be9b20f3-ef3a-4173-a9ed-666b05d6e039)
![Screenshot 2023-09-06 at 9 51 52 AM](https://github.com/wpengine/faustjs/assets/7818951/8aa79289-66bd-41aa-846a-c9dc64a5d79e)
![Screenshot 2023-09-06 at 9 54 33 AM](https://github.com/wpengine/faustjs/assets/7818951/cec77b4e-02b0-4bdd-b74d-53dcc6274af7)

**Comment by stephanonline** [comment]
@JEverhart383 thanks for replying, yes, I found that workaround so it is managable for now. Although it can be annoying.
What I found out is that the button what is referred to in the previewlinks.js is being regenerated and therefor the click event is lost.

**Comment by mindctrl** [comment]
Just noting I just saw this on faustjs.org on the overlay that shows when someone is already editing a post. Screenshot: 
![image](https://github.com/wpengine/faustjs/assets/1254870/82dba1d8-efe0-4f78-a25d-01ab75d57bf2)

The preview URL in the overlay is: `https://faustjs.org/?post_type=faust_tutorial&p=1070&preview=true`.

**Comment by mindctrl** [comment]
I can no longer reproduce this bug. It looks like we fixed it in #1644 and/or #1568. @stephanonline if you're still experiencing this in the latest versions of Faust WP and the packages, feel free to reopen.

**Comment by b00y0h** [comment]
I don't know if this is related, but am getting this error when trying to preview:

Unhandled Runtime Error
Error: The URL must contain the proper "previewPathname" query param for previews.

here's my preview link in WP:
![image](https://github.com/wpengine/faustjs/assets/942414/95df2ab3-fecf-4b80-9bd5-8e645e55a8be)

### Applicable Versions
WordPress plugin version: 1.2.3
WordPress version: 6.4.3
