### ISSUE TITLE
Bug: Replacement of media library URLs in post content

### ISSUE THREAD

**Issue by jamiemorganward** [wpengine/faustjs#1569]
## Applicable Versions

- WordPress plugin version: 1.0.3
- WordPress version: 6.3.1

## Steps To Reproduce

1. Add a link in any post content to an item in the media library (e.g. a PDF for download)
2. Fetch the content using GraphQL and see that the media URL has been replaced with the frontend URL (which is normally not a valid URL).

## The current behavior

`includes/replacement/callbacks.php` is replacing any instance of the `site_url` using `the_content` filter.

## The expected behavior

It should only replace URLs that belong to permalinks, where it might be an internal link and should be handled by the frontend routing. Replacing media URLs will normally break those links.

I've also attempted a fix here to exclude the uploads directory from the replacements: https://github.com/clicksuite/faustjs/commit/cb6dcecfa05ea031e624da54b440440cc78a6860

Another option could be to look for file extensions with a regex similarly to the graphql URL replacement.

Can submit a PR for this if that would be useful!

**Comment by mindctrl** [comment]
@jamiemorganward thank you for reporting this bug. I was able to reproduce this. We'll get this on our backlog ASAP.
