### ISSUE TITLE
Bug: Switching locale does not re-fetch page data with the current locale

### ISSUE THREAD

**Issue by zaironjacobs** [wpengine/faustjs#1570]
Initially, changing the locale also re-fetched the page data with the current locale I'm using in the variables. After installing `next-translate`, also tried `i18next`, it doesn't seem that the current locale is being used in the variables, it seems stuck with the same locale so the page data received isn't in the expected language. Anyone knows what could be the problem here?

## Applicable Versions

- `@faustjs/core` version: 1.1.1

## Steps To Reproduce

1. Install `faustjs` with `next-translate` or `i18next`.
2. Switch locale.

## The current behavior

Page data does not update when the locale is changed.

## The expected behavior

Page data should update when the locale changes.

**Comment by theodesp** [comment]
@zaironjacobs  can you provide a minimal repo for reproducing this problem? Thank you!

**Comment by mindctrl** [comment]
@zaironjacobs we're going to close this issue for now. If you want to re-open this, please feel free to do so.
