### ISSUE TITLE
RFC: Next.js 404 Cache Fix for Faust

### ISSUE THREAD

**Issue by matthewguywright** [wpengine/faustjs#1580]
When using dynamic routes in Next.js, 404 pages get cached for one year by default even without headers. It may be related to [Cache headers on 404 pages with getStaticProps](https://github.com/vercel/next.js/issues/22579).

## Problem Statement

Next.js dynamic routes automatically cache 404 pages for a year, even without headers. This poses an issue for when you want a shorter revalidation time. It creates a situation where updates won't show if a route becomes valid.

For example, you could get HTML from an instance running a previous deploy making a request for a previous artifact (e.g. JS bundle), that request for the artifact gets routed to a new instance (thus 404ing since the hash in the filename is different), and now that 404 is cached at the edge breaking things for everyone until a new rebuild/purge. It can lead to a mixture of 404 and 200 responses depending on the instance accessed.

## Solution

One proposed solution is to add a revalidate option to the 404 route in Faust. Any route that has a 404 fallback will default to a revalidate time of 15 minutes. It would also have the option to let the developer decide the validation time as well if they wished to have a longer cache session than the default.

### Next.js

Since this is a Next.js dynamic router issue, should Next.js come up with a fix? The issue linked below in resources show it as closed even though it still exists as an issue.

### Breaking Change

For previous users their default one year cache from this Next.js issue will be now set to a default revalidation time unless they update their `validate` on the 404 to be longer.

## Resources

- [Cache headers on 404 pages with getStaticProps](https://github.com/vercel/next.js/issues/22579)
- [Internal Jira issue](https://wpengine.atlassian.net/browse/MERL-1232)

**Comment by mindctrl** [comment]
I think we'll want something longer than 1 sec here, which was just an example we used internally when discussing. Thoughts on making it 900 secs (15 mins) to match the default we have elsewhere?

**Comment by theodesp** [comment]
I vote to keep this around 15 minutes just like the Faust default invalidation time. We want to keep a consistent default value to prevent confusion.
