### ISSUE TITLE
Bug: Faust uploads missing block files with blockset command

### ISSUE THREAD

**Issue by JEverhart383** [wpengine/faustjs#1633]
When running `blockset` against a WP Engine hosted WP install, only the `block.json` file appears to sync. A user reported this in this thread [from Discord](https://discord.com/channels/836253505944813629/1171201710685954182), and I was able to reproduce using my own site here: https://faustintl.wpengine.com/

Everything appears to look like it should in `.faust` directory, but accessing `wp-uploads/faust/blocks` only lists the `block.json` file, and the block is not available in the editor.

<img width="373" alt="Screenshot_2023-11-07_at_9 51 56_AM" src="https://github.com/wpengine/faustjs/assets/7818951/6e24a384-1d4c-44c8-bea7-3277b2b65758">
<img width="764" alt="Screenshot_2023-11-07_at_9 52 35_AM" src="https://github.com/wpengine/faustjs/assets/7818951/079c3c43-a4d2-452d-aaaf-943c39bb8970">

The same steps in Local appear to do what I expect, and I can sync and use the block:
<img width="1186" alt="Screenshot_2023-11-07_at_10 10 16_AM" src="https://github.com/wpengine/faustjs/assets/7818951/821ca298-07f1-42e3-b8c8-28cf2e965863">

## Applicable Versions

WordPress: 6.3.1
Faust WordPress Plugin: 1.1.0
WPGraphQL: 1.18.0
@faustwp/core: 1.2.0
@faustwp/cli: 1.2.0
- WordPress version:

## Steps To Reproduce

1. Follow the instructions outlined in this guide: https://faustjs.org/tutorial/react-components-to-gutenberg-blocks

2. Sync blocks to a remote WP install on WP Engine using `blockset`
3. Access `wp-uploads` via FTP to see missing files

Link to code example:

https://github.com/JEverhart383/faust-intl/tree/feature/blockset

## The current behavior
Block sync against a remote WP Engine install fails
## The expected behavior
I should be able to use the block the same way I do on Local

**Comment by theodesp** [comment]
Pinging @josephfusco so that we can take a look. It may be related to WP Engine security rules.

**Comment by theodesp** [comment]
It might be a possible firewall rule since when I run the blockset command I get this response:

```bash
"faust blockset" failed with the following error: Error: Network error: Error uploading to WordPress: {"code":"rest_forbidden","message":"Sorry, you are not allowed to do that.","data":{"status":401}}
    at uploadToWordPress (file:///Users/theo.despoudis/Workspace/atlas-blueprint-blueset/node_modules/@faustwp/cli/dist/blockset.js:104:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async blockset (file:///Users/theo.despoudis/Workspace/atlas-blueprint-blueset/node_modules/@faustwp/cli/dist/blockset.js:149:9)
    at async file:///Users/theo.despoudis/Workspace/atlas-blueprint-blueset/node_modules/@faustwp/cli/dist/index.js:74:13
```

**Comment by theodesp** [comment]
@JEverhart383 We have identified the issue and we are working on a solution.

**Comment by josephfusco** [comment]
I have a [PR open with a proposed fix](https://github.com/wpengine/faustjs/pull/1656)

Also wanted to note that the block-support example project seems to be having issues.
<img width="983" alt="Screenshot 2023-11-14 at 11 36 53 AM" src="https://github.com/wpengine/faustjs/assets/6676674/ed99f6f8-c915-4489-b161-b06d4dcd7a93">

**Comment by josephfusco** [comment]
Ready for another review! :)
https://github.com/wpengine/faustjs/pull/1656
