### ISSUE TITLE
Fix E2E Test Plugin workflow

### ISSUE THREAD

**Issue by ChrisWiegman** [wpengine/faustjs#1695]
Currently the e2e tests are failing most of the time. Example: [E2E Test Plugin · Workflow runs · wpengine/faustjs](https://github.com/wpengine/faustjs/actions/workflows/e2e-test-plugin.yml)

**Comment by mindctrl** [comment]
Last week we fixed an issue in the e2e tests where chromedriver reported that Chrome was crashing. We still have a lingering issue where randomly the import step fails in Codeception. Re-opened this in the project board for visibility.
