### ISSUE TITLE
Verify faust blockset command works properly

### ISSUE THREAD

**Issue by ChrisWiegman** [wpengine/faustjs#1706]
User Story (Required)

As Team Merlin, we want to ensure that the blockset syncing works as intended, so that users are not met with errors when syncing.

Recently we learned that the blockset command was not working well with WPE and some other hosts, due to security configurations that prevent the PHP files from being uploaded to the wp-content/uploads directory. In an attempt to fix this, a PR was created and merged that removes the PHP files and uses the JSON files instead.

However, the missing PHP files causes WP to emit a warning on every page load. Additionally, for at least some of us, the blocks do not show up in the editor.

Acceptance Criteria (Required)

Confirm that the block syncing actually works, and that blocks show up in the editor on: 1) Your local dev site 2) A new site hosted in WP Engine (Start fresh to be sure! We don’t want our bug fix release to not fix the bug!)

If bugs are found, ticket them separately.

Technical Details

TBD

Notes

TBD

**Comment by MattOndo** [comment]
The blockset command does not appear to be syncing correctly for me. I'll drop the console logs below. It compiles, but does not create the zip nor sync it to my local WP site (using the Local app)

Additional details:
- MacOS Latest
- Node v20.9.0
- Using yarn (v 1.22.21)
- Using the /src/ directory, my structure is:

```
./
├── src/
│   └── wp-blocks/
│       └── TestButton/
│           └── block.json
│           └── index.js
│           └── style.css
│           └── TestButton.js
...
```

Console logs after running `faust blockset`:

```bash
yarn blockset
yarn run v1.22.21
$ yarn faust blockset
$ /Users/XXXXXXXX/Projects/XXXXXXXX/faust-demo/node_modules/.bin/faust blockset
debug - Faust is running in debug mode
warn - Your WordPress site is not running on https!
warn - This is a security concern as all traffic with your secret key is in plain text.
warn - Please make sure your production Faust app runs with a WordPress instance on https!
debug - Discoverd GraphQL endpoint at http://faust-demo.local/index.php?graphql
info - Faust: Compiling Blocks into /Users/XXXXXXXX/Projects/XXXXXXXX/faust-demo/.faust/build
assets by chunk 45.6 KiB (name: wp-blocks/TestButton/index)
  asset wp-blocks/TestButton/index.js 45.4 KiB [emitted] (name: wp-blocks/TestButton/index) 1 related asset
  asset wp-blocks/TestButton/index.asset.php 152 bytes [emitted] (name: wp-blocks/TestButton/index)
asset wp-blocks/TestButton/block.json 752 bytes [emitted] [from: src/wp-blocks/TestButton/block.json] [copied]
asset wp-blocks/TestButton/style-index.css 564 bytes [emitted] (name: wp-blocks/TestButton/style-index) (id hint: style)
Entrypoint wp-blocks/TestButton/index 46.1 KiB (29.8 KiB) = wp-blocks/TestButton/style-index.css 564 bytes wp-blocks/TestButton/index.js 45.4 KiB wp-blocks/TestButton/index.asset.php 152 bytes 1 auxiliary asset
runtime modules 4.31 KiB 10 modules
orphan modules 3.23 KiB [orphan] 3 modules
cacheable modules 15.5 KiB (javascript) 0 bytes (css/mini-extract)
  modules by path ./node_modules/@faustwp/block-editor-utils/dist/mjs/ 12.7 KiB 18 modules
  modules by path ./src/wp-blocks/TestButton/ 2.84 KiB (javascript) 0 bytes (css/mini-extract)
    javascript modules 2.27 KiB 3 modules
    ./src/wp-blocks/TestButton/block.json 585 bytes [built] [code generated]
    css ./node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[2].use[1]!./node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[2].use[2]!./src/wp-blocks/TestButton/style.css 0 bytes [built] [code generated]
external "React" 42 bytes [built] [code generated]
external ["wp","blocks"] 42 bytes [built] [code generated]
external ["wp","blockEditor"] 42 bytes [built] [code generated]
external ["wp","components"] 42 bytes [built] [code generated]
external ["wp","hooks"] 42 bytes [built] [code generated]
webpack 5.89.0 compiled successfully in 796 ms
```

It just hangs out there until a file change then re-runs. The result is:
- Creates empty `.faust/blocks` and `.faust/build` directories in the root
- Compiles the block to `/build/wp-blocks/TestButton/` which includes:
  - block.json
  - index.asset.php
  - index.js
  - index.js.map
  - style-index.css
- Does not generate a .zip file
- Does not sync to the WP site (used to go to wp-content/uploads/faust/blocks I think?)
- Does not generate a manifest

**Comment by mindctrl** [comment]
Documenting my findings...

First pass on a new site on my local machine using Local by WPE. Will be testing a WPE-hosted site afterwards.

## Setup
- Local 8.1.0
- WP 6.4.2
- PHP 8.1.23
- FaustWP plugin - canary branch
- WPGraphQL 1.19.0
- block-support example from canary branch, installed using the following:
```
npx create-next-app \
    -e https://github.com/wpengine/faustjs/tree/canary \
    --example-path examples/next/block-support \
    --use-npm
```

`npm run blockset` worked fine. The example blocks show up in WP.

## Screenshot of blocks in wp-admin
![image](https://github.com/wpengine/faustjs/assets/1254870/7a73072a-4156-4d06-93a3-b7dfbeb05c26)

## Tree listing of `wp-content/uploads/faustwp/blocks`
```
pwd
~/Sites/blockset/app/public/wp-content/uploads/faustwp/blocks
➜  blocks tree
.
├── block-a
│   ├── block.json
│   ├── index.asset.php
│   ├── index.css
│   ├── index.css.map
│   ├── index.js
│   ├── index.js.map
│   ├── style-index.css
│   └── style-index.css.map
├── block-b
│   ├── block.json
│   ├── index.asset.php
│   ├── index.js
│   ├── index.js.map
│   ├── style-index.css
│   └── style-index.css.map
├── blocks.zip
└── manifest.json

3 directories, 16 files
```

**Comment by mindctrl** [comment]
Attempts to use blockset on WPE hosted site. Still debugging this.

## Setup
- WP 6.4.2
- PHP 8.2
- Node v18.16.1
- NPM 9.5.1
- FaustWP plugin - canary branch
- WPGraphQL 1.19.0
- block-support example from canary branch, installed using the following:
```
npx create-next-app \
    -e https://github.com/wpengine/faustjs/tree/canary \
    --example-path examples/next/block-support \
    --use-npm
```

`npm run blockset` errors, with the following:

```
"faust blockset" failed with the following error: Error: Network error: Cannot follow redirect with body being a readable stream
```

**Comment by mindctrl** [comment]
An older WPE hosted site

## Setup
- WP 6.4.2
- PHP 7.4.33.4
- 

`npm run blockset` errors with the following:
```
"faust blockset" failed with the following error: Error: Network error: Error uploading to WordPress: {"code":"copy_failed_ziparchive","message":"Could not copy file.","data":"block-a\/index.asset.php"}
```

**Comment by blakewilson** [comment]
I just tested the latest changes against Local and a WPE hosted site and both worked as expected for me:

## WPE Hosted site:

### Setup

- WP 6.3.2
- PHP 7.4
- Node 18.17.0
- NPM 10.2.5
- FaustWP Plugin - canary branch (zipped from source)
- WPGraphQL 1.19.0

`npm run blockset` was ran from the monorepo `block-support` example to ensure latest code changes.

### CLI Output

```
> @faustwp/block-support-example@0.1.0 blockset
> faust blockset

npm verb cli /Users/blakewilson/.nvm/versions/node/v18.17.0/bin/node /Users/blakewilson/.nvm/versions/node/v18.17.0/bin/npm
npm info using npm@10.2.5
npm info using node@v18.17.0
npm info found workspace root at /Users/blakewilson/wpengine/faustjs 
npm verb title npm exec wp-scripts start --no-watch --webpack-src-dir=wp-blocks --output-path=/Users/blakewilson/wpengine/faustjs/examples/next/block-support/.faust/build
npm verb argv "exec" "wp-scripts" "start" "--package" "@wordpress/scripts" "--loglevel" "verbose" "--" "--no-watch" "--webpack-src-dir=wp-blocks" "--output-path=/Users/blakewilson/wpengine/faustjs/examples/next/block-support/.faust/build"
npm verb logfile logs-max:10 dir:/Users/blakewilson/.npm/_logs/2024-01-11T19_21_44_890Z-
npm verb logfile /Users/blakewilson/.npm/_logs/2024-01-11T19_21_44_890Z-debug-0.log
assets by path block-a/ 19 KiB
  assets by chunk 17.4 KiB (name: block-a/index)
    asset block-a/index.js 16.3 KiB [emitted] (name: block-a/index) 1 related asset
    asset block-a/index.css 1.03 KiB [emitted] (name: block-a/index) 1 related asset
    asset block-a/index.asset.php 134 bytes [emitted] (name: block-a/index)
  asset block-a/style-index.css 1.09 KiB [emitted] (name: block-a/style-index) (id hint: style) 1 related asset
  asset block-a/block.json 453 bytes [emitted] [from: wp-blocks/block-a/block.json] [copied]
assets by path block-b/ 188 KiB
  assets by chunk 186 KiB (name: block-b/index)
    asset block-b/index.js 186 KiB [emitted] (name: block-b/index) 1 related asset
    asset block-b/index.asset.php 152 bytes [emitted] (name: block-b/index)
  asset block-b/style-index.css 1.13 KiB [emitted] (name: block-b/style-index) (id hint: style) 1 related asset
  asset block-b/block.json 690 bytes [emitted] [from: wp-blocks/block-b/block.json] [copied]
Entrypoint block-a/index 18.5 KiB (12.7 KiB) = block-a/style-index.css 1.09 KiB block-a/index.css 1.03 KiB block-a/index.js 16.3 KiB block-a/index.asset.php 134 bytes 3 auxiliary assets
Entrypoint block-b/index 187 KiB (184 KiB) = block-b/style-index.css 1.13 KiB block-b/index.js 186 KiB block-b/index.asset.php 152 bytes 2 auxiliary assets
orphan modules 1.01 MiB (javascript) 997 bytes (runtime) [orphan] 254 modules
runtime modules 9.08 KiB 20 modules
built modules 132 KiB (javascript) 756 bytes (css/mini-extract) [built]
  modules by path ../../../ 127 KiB
    modules by path ../../../node_modules/ 113 KiB
      modules by path ../../../node_modules/graphql/ 92.7 KiB 18 modules
      + 2 modules
    modules by path ../../../packages/block-editor-utils/dist/mjs/ 13.9 KiB 19 modules
  modules by path ./wp-blocks/ 5.47 KiB (javascript) 756 bytes (css/mini-extract)
    modules by layer 5.47 KiB 10 modules
    css modules 756 bytes
      css ../../../node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[4].use[1]!../../../node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[4].use[2]!../../../node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[4].use[3]!./wp-blocks/block-a/style.scss 262 bytes [built] [code generated]
      + 2 modules
  + 6 modules
webpack 5.89.0 compiled successfully in 1870 ms
npm verb exit 0
npm info ok 
✅ Blockset sync complete!
```

Blocks are visible in the blocks pane:
![Image](https://github.com/wpengine/faustjs/assets/5946219/e579c4b0-93f7-41dc-90f9-62ef9dbe785e)

## Local WP site:

### Setup

- WP 6.4.2
- PHP 8.2.10
- Node 18.17.0
- NPM 10.2.5
- FaustWP Plugin - canary branch (zipped from source)
- WPGraphQL 1.17.0

`npm run blockset` was ran from the monorepo `block-support` example to ensure latest code changes.

### CLI Output

```
> @faustwp/block-support-example@0.1.0 blockset
> faust blockset

warn - Your WordPress site is not running on https!
warn - This is a security concern as all traffic with your secret key is in plain text.
warn - Please make sure your production Faust app runs with a WordPress instance on https!
npm verb cli /Users/blakewilson/.nvm/versions/node/v18.17.0/bin/node /Users/blakewilson/.nvm/versions/node/v18.17.0/bin/npm
npm info using npm@10.2.5
npm info using node@v18.17.0
npm info found workspace root at /Users/blakewilson/wpengine/faustjs 
npm verb title npm exec wp-scripts start --no-watch --webpack-src-dir=wp-blocks --output-path=/Users/blakewilson/wpengine/faustjs/examples/next/block-support/.faust/build
npm verb argv "exec" "wp-scripts" "start" "--package" "@wordpress/scripts" "--loglevel" "verbose" "--" "--no-watch" "--webpack-src-dir=wp-blocks" "--output-path=/Users/blakewilson/wpengine/faustjs/examples/next/block-support/.faust/build"
npm verb logfile logs-max:10 dir:/Users/blakewilson/.npm/_logs/2024-01-11T19_24_21_508Z-
npm verb logfile /Users/blakewilson/.npm/_logs/2024-01-11T19_24_21_508Z-debug-0.log
assets by path block-a/ 19 KiB
  assets by chunk 17.4 KiB (name: block-a/index)
    asset block-a/index.js 16.3 KiB [emitted] (name: block-a/index) 1 related asset
    asset block-a/index.css 1.03 KiB [emitted] (name: block-a/index) 1 related asset
    asset block-a/index.asset.php 134 bytes [emitted] (name: block-a/index)
  asset block-a/style-index.css 1.09 KiB [emitted] (name: block-a/style-index) (id hint: style) 1 related asset
  asset block-a/block.json 453 bytes [emitted] [from: wp-blocks/block-a/block.json] [copied]
assets by path block-b/ 188 KiB
  assets by chunk 186 KiB (name: block-b/index)
    asset block-b/index.js 186 KiB [emitted] (name: block-b/index) 1 related asset
    asset block-b/index.asset.php 152 bytes [emitted] (name: block-b/index)
  asset block-b/style-index.css 1.13 KiB [emitted] (name: block-b/style-index) (id hint: style) 1 related asset
  asset block-b/block.json 690 bytes [emitted] [from: wp-blocks/block-b/block.json] [copied]
Entrypoint block-a/index 18.5 KiB (12.7 KiB) = block-a/style-index.css 1.09 KiB block-a/index.css 1.03 KiB block-a/index.js 16.3 KiB block-a/index.asset.php 134 bytes 3 auxiliary assets
Entrypoint block-b/index 187 KiB (184 KiB) = block-b/style-index.css 1.13 KiB block-b/index.js 186 KiB block-b/index.asset.php 152 bytes 2 auxiliary assets
orphan modules 1.01 MiB (javascript) 997 bytes (runtime) [orphan] 254 modules
runtime modules 9.08 KiB 20 modules
built modules 132 KiB (javascript) 756 bytes (css/mini-extract) [built]
  modules by path ../../../ 127 KiB
    modules by path ../../../node_modules/ 113 KiB
      modules by path ../../../node_modules/graphql/ 92.7 KiB 18 modules
      + 2 modules
    modules by path ../../../packages/block-editor-utils/dist/mjs/ 13.9 KiB 19 modules
  modules by path ./wp-blocks/ 5.47 KiB (javascript) 756 bytes (css/mini-extract)
    modules by layer 5.47 KiB 10 modules
    css modules 756 bytes
      css ../../../node_modules/css-loader/dist/cjs.js??ruleSet[1].rules[4].use[1]!../../../node_modules/postcss-loader/dist/cjs.js??ruleSet[1].rules[4].use[2]!../../../node_modules/sass-loader/dist/cjs.js??ruleSet[1].rules[4].use[3]!./wp-blocks/block-a/style.scss 262 bytes [built] [code generated]
      + 2 modules
  + 6 modules
webpack 5.89.0 compiled successfully in 1391 ms
npm verb exit 0
npm info ok 
✅ Blockset sync complete!
```

Blocks are visible in the blocks pane:
![Image](https://github.com/wpengine/faustjs/assets/5946219/09402273-73d2-4da1-a5d4-243dde21a090)

However, with `WP_DEBUG` enabled I did notice this warning (I do think this was already mentioned though and it's being tracked):
![Image](https://github.com/wpengine/faustjs/assets/5946219/9f446803-7bd5-4060-9e2d-1712e6edafb7)

**Comment by mindctrl** [comment]
Turns out I had plain permalinks enabled, which causes a redirect on the WP site when hitting `/wp-json`. We can update that to always hit the `?rest_route=` variant. I'm ticketing that separately though, due to the heavy amount of testing that has gone into this as is.

**Comment by stackjo** [comment]
> Hey @mindctrl did you ever manage to fix the issue with the custom block not being visible in the wordpress block editor? I'm facing the same issue but for me, like others in the thread, a index.asset.php is not being generated either.

Hello, for anyone who stumbles across this in the future. 

I had forgot to set the Config property on my block component

MyFirstBlock.config = {
  name: "CreateBlockMyFirstBlock",
  editorFields: {
    message: {
      type: "string",
      label: "My Message",
      location: "editor",
    },
  },
};


I didn't even think that would be an issue since in the guide they move on to "taking a look in the editor" before writing about the config part.

I only noticed this once I compared the example blocks project and my own project.

And for the record it does not seem like the index.asset.php has anything to do with my issues at least.

**Comment by cguagenti** [comment]
I had issues with WordPress 6.5 where blocks where not visible after running `npm run blockset`.

It seems 6.5 needs the `index.asset.php` in order to prioritize the assets. 

In the `blockset.ts` -> `processBlockFiles()` there is the below block. I commented it and it works.

`// Handle PHP asset file
        const phpAssetPath = path.join(blockDir, 'index.asset.php');
        if (await fs.pathExists(phpAssetPath)) {
            const phpContent = await fs.readFile(phpAssetPath, 'utf8');
            const assetData = parsePhpAssetFile(phpContent);
            await fs.writeJson(path.join(destDir, 'index.asset.json'), assetData, {
                spaces: 2,
            });
            await fs.remove(phpAssetPath);
        }
        // Remove any other PHP files
        const phpFiles = await glob(`${destDir}/**/*.php`, {
            ignore: IGNORE_NODE_MODULES,
        });
        await Promise.all(phpFiles.map((file) => fs.remove(file)));`

**Comment by jan-clockworkwp** [comment]
Same issue here: no generated blocks are visible in the Gutenberg editor in WordPress since version 6.5, unless you keep the `index.asset.php` file in the generated block folder. 
Thanks, @cguagenti, your quick fix worked for me as well. I also tried the latest canary version of `@faustwp/cli` package, and the same issue was experienced. 
In addition to @cguagenti's suggestion, dirty fix change needs to be made in the `/dist` folder rather than the `/src` folder where the `blockset.ts` file is located. In my case, it worked fine by removing the code block in `node_modules/@faustwp/cli/dist/blockset.js` file. 
I am just wondering, @blakewilson, could a proper solution for this issue be included in the next package release? What would be the best solution for this issue, just excluding this particular `index.asset.php` file from removal, rather than removing whole code block? Many thanks!
