### ISSUE TITLE
[Bug] Faust Core: useAuth hook is getting called by default for unauthenticated users triggering extra API calls

### ISSUE THREAD

**Issue by theodesp** [wpengine/faustjs#1722]
# Versions affected

@faustwp-core: 2.0.0

# Description
When navigating to any page you can see extra API calls to the Faust auth token endpoint when the user is not authenticated.

# Steps to reproduce

1. Set experimental toolbar: `false`
2. Visit any page.
3. You should see a call to the `/api/faust/auth/token` endpoint even though the user is not authenticated.

![Image](https://github.com/wpengine/faustjs/assets/328805/3da09b9f-de07-4bd6-b9aa-08bf32d7dfe4)

# Technical Details
* There is a call to the useAuth hook be default on the `WordPressTemplate` component here:

[`WordPressTemplate`](https://github.com/wpengine/faustjs/blob/canary/packages/faustwp-core/src/components/WordPressTemplate.tsx#L193-L196)

However this happens on every render so it produces additional API calls that can trigger service degradation
We should restore the original functionality which by default it does not trigger this extra auth call.

* When experimental toolbar: `true` then the toolbar also triggers an API call. This could be addressed in another ticket.
* We should ensure authorization only when the page requested is `Preview`

**Comment by mindctrl** [comment]
Related https://github.com/wpengine/faustjs/issues/1657
