### ISSUE TITLE
Update Faustjs.org Site Plugins

### ISSUE THREAD

**Issue by ChrisWiegman** [wpengine/faustjs#1728]
The plugins on https://faustjs.org are out of date and require an update. This ticket is to do so and to ensure that SPM is turned on to automagically update the plugins in the future.

## Acceptance Criteria

- [x] Update any out of date plugins on faustjs.org
- [x] Activate [SPM](https://wpengine.com/support/smart-plugin-manager/) on the Faust site to ensure that plugins are kept up to date in the future.

**Comment by TeresaGobble** [comment]
Note that we may not have a license for SPM and might need to get that before finishing this ticket out. 👍
