### ISSUE TITLE
Bug: Experimental App Router Breaks when used with newest version of @faustwp/core 2.1

### ISSUE THREAD

**Issue by CesarBenavides777** [wpengine/faustjs#1746]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@faustwp/core@2.1.0` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@faustwp/core/dist/mjs/store/FaustContext.js b/node_modules/@faustwp/core/dist/mjs/store/FaustContext.js
index 6f696bb..f4e2f87 100644
--- a/node_modules/@faustwp/core/dist/mjs/store/FaustContext.js
+++ b/node_modules/@faustwp/core/dist/mjs/store/FaustContext.js
@@ -1,2 +1,6 @@
+"use client";
+
+"use client";
+
 import { createContext } from 'react';
 export const FaustContext = createContext(undefined);
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by CesarBenavides777** [comment]
@theodesp I get this error when trying to import like in the example:

![image](https://github.com/wpengine/faustjs/assets/17585202/b1945499-dae1-4a36-aec8-462e8fbb3453)


I get around it by importing as such:
````
// @ts-expect-error
import { FaustProvider } from "@faustwp/experimental-app-router/ssr";
````

Any insight on why this happens?

**Comment by CesarBenavides777** [comment]
I still have to patch the package otherwise I get this error:
````
Server Error
Error: (0 , react__WEBPACK_IMPORTED_MODULE_0__.createContext) is not a function

This error happened while generating the page. Any console logs will be displayed in the terminal window.
Call Stack
undefined
node_modules/@faustwp/core/dist/mjs/store/FaustContext.js (2:42)
(rsc)/./node_modules/@faustwp/core/dist/mjs/store/FaustContext.js
file:///Users/CESARMAC/Desktop/ENV/book-of-free/.next/server/vendor-chunks/@faustwp.js (610:1)
__webpack_require__
file:///Users/CESARMAC/Desktop/ENV/book-of-free/.next/server/webpack-runtime.js (33:42)
eval
webpack-internal:///(rsc)/./node_modules/@faustwp/core/dist/mjs/components/FaustProvider.js (11:80)
(rsc)/./node_modules/@faustwp/core/dist/mjs/components/FaustProvider.js
file:///Users/CESARMAC/Desktop/ENV/book-of-free/.next/server/vendor-chunks/@faustwp.js (180:1)
__webpack_require__
file:///Users/CESARMAC/Desktop/ENV/book-of-free/.next/server/webpack-runtime.js (33:42)
eval
webpack-internal:///(rsc)/./node_modules/@faustwp/core/dist/mjs/index.js (36:86)
(rsc)/./node_modules/@faustwp/core/dist/mjs/index.js
file:///Users/CESARMAC/Desktop/ENV/book-of-free/.next/server/vendor-chunks/@faustwp.js (410:1)
__webpack_require__
file:///Users/CESARMAC/Desktop/ENV/book-of-free/.next/server/webpack-runtime.js (33:42)
eval
webpack-internal:///(rsc)/./components/footer.tsx (9:71)
(rsc)/./components/footer.tsx
file:///Users/CESARMAC/Desktop/ENV/book-of-free/.next/server/app/login/page.js (1169:1)
__webpack_require__
file:///Users/CESARMAC/Desktop/ENV/book-of-free/.next/server/webpack-runtime.js (33:42)
eval
````

**Comment by blakewilson** [comment]
@CesarBenavides777 Looks like this is happening on the `app/login/page.js`, is that right?

Could you paste that page (specifically the imports)? It looks like you may be importing something from Faust core that you shouldn't be.

**Comment by CesarBenavides777** [comment]
@blakewilson no this happens everywhere, not just on the login page.

For some reason just adding "use client" fixes it. 

Would it be helpful if I sent you my repo? It's private but I can zip it up for you.

**Comment by theodesp** [comment]
@CesarBenavides777 a reproduction example would be helpful. Thank you.

**Comment by blakewilson** [comment]
Hey @CesarBenavides777, I am unable to replicate this with the example project using the latest Faust versions:

```
npx create-next-app \
    -e https://github.com/wpengine/faustjs/tree/main \
    --example-path examples/next/faustwp-getting-started \
    --use-npm
```

Could you create a public repo with a minimal reproduction?

You could also start with your project and remove things step by step until the build succeeds to determine what is causing this issue.

**Comment by CesarBenavides777** [comment]
@blakewilson yes looks to be fixed!

I did have to change my tsconfig like so:
````
    "module": "esnext",
    "moduleResolution": "node",
````
TO:
````
    "module": "ESNext",
    "moduleResolution": "Bundler",
````

**Comment by CesarBenavides777** [comment]
@blakewilson yes looks to be fixed!

I did have to change my tsconfig like so:
````
    "module": "esnext",
    "moduleResolution": "node",
````
TO:
````
    "module": "ESNext",
    "moduleResolution": "Bundler",
````

Closing

**Comment by blakewilson** [comment]
@CesarBenavides777 Awesome! I'm glad you got it working.
