### ISSUE TITLE
[Faust.js] Replace CI/CD Pipeline with WP-GraphQL pipeline

### ISSUE THREAD

**Issue by theodesp** [wpengine/faustjs#1752]
# Description
Instead of using our own custom CI/CD pipeline to test the plugin and setting up the Docker WordPress tests we should re-use the one from WP-GraphQL since its more standardised.

# Technical Details
- Use this pipeline making sure the references are correct:

 https://github.com/wp-graphql/wp-graphql/tree/develop/docker

**Comment by ChrisWiegman** [comment]
As we're already updating the pipeline here for Playwright and other features, this ticket is obsolete and I am closing it.
