### ISSUE TITLE
Audit Next.js Defaults and Settings

### ISSUE THREAD

**Issue by ChrisWiegman** [wpengine/faustjs#1756]
Next.js default settings such as how content headers are set may not be appropriate for Faust.js. This ticket is to audit the current settings and defaults in Next.js and review how they relate to Faust so we can ticket improvements around 3 major focuses: security, performance and developer experience. 

The spirit of this ticket is for us to value decisions over options, just like WordPress core, so that folks building with Faust have that much less to think about when they deploy their first project or their 100th project.

## Acceptance Criteria

- [ ] Audit Next.js defaults and settings around performance, security and developer experience
- [ ] Ticket appropriate changes to Faust so that settings and defaults align better with the best practices of Faust.js and WordPress.

## Technical Details
- Audit Next.js headers configuration: https://nextjs.org/docs/pages/api-reference/next-config-js/headers
- Audit Next.js Content Security Policy: https://nextjs.org/docs/app/building-your-application/configuring/content-security-policy
- Audit Next.js Optimization docs: https://nextjs.org/docs/app/building-your-application/optimizing

**Comment by ChrisWiegman** [comment]
This ticket was prompted by a chat with @jasonbahl.

I do think we'll need some discussion here to narrow scope but I'll leave the description as it is for today until we can properly refine the scope further as a team through our normal process and additional discussion.

**Comment by mindctrl** [comment]
Related: #1780
