### ISSUE TITLE
[Faust.js] Add debugging instructions for VsCode + provide sample .vscode config

### ISSUE THREAD

**Issue by theodesp** [wpengine/faustjs#1765]
# Description

We should provide detailed instructions on how to debug Next.js Apps with Chrome.

# Acceptance Criteria

- Debugging How To Guide added in Faustjs.org
- Sample vscode launch.json added in example projects

# Technical reference
- See example config from Blitz framework: https://blitzjs.com/docs/troubleshooting#vscode

**Comment by theodesp** [comment]
https://faustjsorg.wpengine.com/wp-admin/post.php?post=1003&action=edit

**Comment by blakewilson** [comment]
Well done @theodesp, looks great. I can't seem to find the approve button on the site, so here's my approval!
