### ISSUE TITLE
[Faust.js]  Document Apollo Client DevTools usage

### ISSUE THREAD

**Issue by theodesp** [wpengine/faustjs#1766]
# Description

Apollo Client Devtools is a Chrome extension for the open-source GraphQL client, Apollo Client.
It is enabled by default on Dev mode so we need a small guide on how to use this tool with Faust.

# Acceptance Criteria

- How to use DevTools page added in Faustjs.org

**Comment by theodesp** [comment]
https://faustjsorg.wpengine.com/wp-admin/post.php?post=979&action=edit

**Comment by TeresaGobble** [comment]
Hi @theodesp! This looks great, thank you for putting this too together for folks. I've been looking over the doc, and have hit a snag out of the gate. I have not been able to get the Apollo tab to show up in devtools. I've closed and restarted Chrome (and Firefox when testing in that browser), ensured it is enabled under my browser's extensions settings page, have removed and re-installed the Apollo devtools extension, have stopped/started the example project with the faust dev command, and have been combing though the Apollo devtools support forum to try to find a solution as to why it is not showing up- but no dice. Can we take a look together and document any helpful steps we uncover for users?

**Comment by mindctrl** [comment]
@TeresaGobble I'm curious how the extension is configured in your end.

Screenshot:
![Image](https://github.com/wpengine/faustjs/assets/1254870/4fdc6110-d73b-4943-a073-5d8333c5f47f)
