### ISSUE TITLE
[SPIKE] Research ways to improve PageSpeed scores with Faust

### ISSUE THREAD

**Issue by ChrisWiegman** [wpengine/faustjs#1780]
On thing we're seeing reported quite frequently in production is sub-optimal PageSpeed scores with Faust.js. This ticket is to review and ticket ways we can improve our pagespeed scores via code and documentation.

**Comment by blakewilson** [comment]
Document worth considering when talking page speed.

https://docs.google.com/document/d/1VSBfRb4BwKAocibYyI8xU0F8fVl9gEJRqLAKxRxQsZE/edit#heading=h.no0yji5jyjn1

**Comment by blakewilson** [comment]
My findings are in the below Google Doc. Upon team agreement I will make tickets for the items:

https://docs.google.com/document/d/14JLi8lUwBgpGQL5tbnTetlZxDX6c8AN-fAXh4OoJSpQ/edit
