### ISSUE TITLE
Ensure previews are not cached when using Faust templates

### ISSUE THREAD

**Issue by ChrisWiegman** [wpengine/faustjs#1782]
## User Story (Required)

As a Faust user who uses previews in their Faust templates, I want to automatically have Apollo set no-fetch options and/or set a cache buster SHA on the URL so that I can get fresh data every time regardless of using Smart Cache/GET requests/persisted queries.

This was brought up by @Jason Bahl and someone in the [WPGraphQL slack](https://wp-graphql.slack.com/archives/C3NM1M291/p1696037648251299). This user has some good ideas on how they implemented it. Maybe we could implement something similar for all Faust users.

## Acceptance Criteria (Required)

- [ ] Previews used in Faust Templates are never cached.

## Technical Details

* TBD

## Notes

* TBD

**Comment by mindctrl** [comment]
The example solution is unavailable now due to the limitations of free Slack accounts.

**Comment by ChrisWiegman** [comment]
Closing as a stale bug. As we focus more on the App Router we can revisit this should it be asked for.
