### ISSUE TITLE
Bug: preview not working when post permalink is rewriting

### ISSUE THREAD

**Issue by MKlblangenois** [wpengine/faustjs#1792]
## Environment
- `faustwp` plugin version: 1.2.1
- WordPress version: 6.4.3
- Browser, OS, and other relevant software versions: Brave, Mac OS 14.0

## Description
When I rewrite permalink for post type to add path before the slug of my post, preview link inside Gutenberg isn't modified to fit the NextJS front URL.

## Steps to Reproduce
1. Rewrite the slug of post type
```php
/**
 * Custom post types
 * 
 * @package FaustPress
 * 
 * @since 1.0.0
 */
class FaustPressCPT extends FaustPress {
	public function __construct() {
		// ...
		add_filter('post_link', array($this, 'rewrite_post_slug'), 10, 2);
	}

        // ...

	/**
	 * Rewrite post slug to add "actualites" translated before the slug
	 *
	 * @param string $slug
	 * @param string $post_ID
	 * 
	 * @return string
	 */
	public function rewrite_post_slug($url, $post) {
		if ($post->post_type == 'post') {
			$url = "/" . __("actualites", $this->theme_textdomain) . "/" . $post->post_name . '/';
		}

		return $url;
	}
}
```
2. Go to a post
3. Go on "preview" button or click on it to see the URL

On page:
![image](https://github.com/wpengine/faustjs/assets/42929225/c1de3e32-5bd7-4d87-8682-ec9461224a5b)

On post: 
![image](https://github.com/wpengine/faustjs/assets/42929225/9178bcc6-c41f-4f7d-9f2d-6bd7331795db)

**Comment by TeresaGobble** [comment]
Thank you for the report, @MKlblangenois! We'll move forward with reproducing this and plan out next steps.

**Comment by TeresaGobble** [comment]
Hi @MKlblangenois, Thank you for your patience. I talked to me team, and it looks like you're using a WordPress hook for Gutenberg that doesn't have parity with Gutenberg functionality. The hook that may be of better use to you is https://developer.wordpress.org/reference/hooks/preview_post_link/

I would also suggest taking a look at functionality in Faust that may be what you're hoping to emulate here. It's a callback for the WordPress 'preview_post_link' filter which swaps the post preview link for your headless front-end and supports the Next.js preview mode:

https://github.com/wpengine/faustjs/blob/4724719eaa36295733955d47ad98c43e06ebc1f7/plugins/faustwp/includes/replacement/callbacks.php#L137-L231  

I hope this helps!

**Comment by MKlblangenois** [comment]
Hi @TeresaGobble!

Thanks for the help!

It's look like doing something like that make the job:
```php
/**
 * Rewrite post slug to add "actualites" translated before the slug
 *
 * @param string $slug
 * @param string $post_ID
 * 
 * @return string
 */
public function rewrite_post_slug($url, $post) {
	if ($post->post_type == 'post') {
		$url = "/" . __("actualites", $this->theme_textdomain) . "/" . $post->post_name . '/';
	}

	return $url;
}

/**
 * Update the preview post link for "post" to using preview_post_link filter
 *
 * @param string $url
 * @param WP_Post $post
 * 
 * @return string
 */
public function update_preview_post_link($url, $post) {
	if ($post->post_type == 'post') {
		$url = "/" . __("actualites", $this->theme_textdomain) . "/" . $post->post_name . '/';
	}

	return $url;
}
```

If that could help someone in the future.

Thanks again!

**Comment by TeresaGobble** [comment]
Awesome, thank you @MKlblangenois !
