### ISSUE TITLE
Update Toolbar docs to include how to authenticate on the frontend

### ISSUE THREAD

**Issue by blakewilson** [wpengine/faustjs#1810]
From the toolbar perspective, you can only authenticate via "previewing" a post. Let's add to the docs how to create a frontend login page to facilitate login and easier access to the toolbar.

See the toolbar example for how login works here:
https://github.com/wpengine/faustjs/blob/canary/examples/next/custom-toolbar/wp-templates/front-page.js

Review document here: https://faustjsorg.wpengine.com/wp-admin/post.php?post=1097&action=edit

**Comment by mindctrl** [comment]
Looks good to me @TeresaGobble!
