### ISSUE TITLE
SSR only works when template query is present

### ISSUE THREAD

**Issue by rrmesquita** [wpengine/faustjs#1813]
### Description

When a template component doesn't have a `query` property, the SSR for that page simply doesn't work.

It looks like a bug to me because it doesn't make sense – if a page doesn't require remote data, there's no reason not to generate it statically.

In my reproduction example, I added a query to fetch some unused piece of data, just to show that the sole presence of a query triggers the SSR.

### Steps to reproduce

1. Clone my [reproduction repository](https://github.com/rrmesquita/wpengine-faustjs-ssr-issue)
2. Install dependencies, run the build then `npm run start` to start the server
3. In the browser, navigate to [/sample-page](http://localhost:3000/sample-page)
4. Right-click and "View Page Source"
5. Search for "testing" and assert **it is not** there
6. Stop the server, go to `wp-templates/page.js`, uncomment the template query and save the file
7. Run the build and start the server again
8. Update the View Source page
9. Search for "testing" and assert **it is** there.

### Additional context

Page Source screenshot:

<img width="682" alt="Screenshot 2024-02-21 at 22 02 59" src="https://github.com/wpengine/faustjs/assets/30835404/a17d046e-2c4b-407a-963c-99d8ecde8e7e">

### @faustwp/core Version

2.1.2

### @faustwp/cli Version

2.0.0

### FaustWP Plugin Version

Using hosted example

### WordPress Version

Using hosted example

### Additional environment details

Using hosted example

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

**Comment by jasonbahl** [comment]
@rrmesquita thanks for reporting this! 

I'd be curious to hear more about your use case for using a wp-template file if you don't require data from WordPress?

**Comment by rrmesquita** [comment]
@jasonbahl I may have expressed myself poorly. Sorry about it.

I do require data from WordPress. Actually, my use case is exactly the one described in the RFC: multiple queries, one being the page data and the other being layout/global pieces of content.

But when trying out with multiple queries and seeing that the SSR was not working, I discovered the problem described in this issue.

Let me know if I can provide more details.

**Comment by jasonbahl** [comment]
To clarify, you have `Component.query` _or_ `Component.queries` the SSR works, but if neither are there it doesn't work and an error or some sort of debug messaging would be expected?

**Comment by rrmesquita** [comment]
I've updated my reproduction repo to include an example of multi queries, where the SSR also doesn't work.

**Comment by theodesp** [comment]
@rrmesquita I tried to reproduce your example but it seems that everything works as expected

**Production build with no Component.query**
<img width="1249" alt="Screenshot 2024-02-22 at 14 16 37" src="https://github.com/wpengine/faustjs/assets/328805/2cd26735-052b-4ea6-8f42-138f74cad440">

**Production build with Component.query**
<img width="1266" alt="Screenshot 2024-02-22 at 14 17 15" src="https://github.com/wpengine/faustjs/assets/328805/73a5b6b1-f8ef-4694-ae44-9221037ca205">

**Production build with Component.queries**
<img width="1265" alt="Screenshot 2024-02-22 at 14 18 02" src="https://github.com/wpengine/faustjs/assets/328805/79d58619-2d4d-4945-9230-44990913c2cc">


is there something we miss?

**Comment by rrmesquita** [comment]
@theodesp your screenshots show you're looking at the DOM inspection, rather than the actual page source. By the time you're looking at the DOM, the page has already been parsed and the JavaScript has already been executed. The DOM is the result of the JavaScript execution, not the source of the page.

**Comment by jasonbahl** [comment]
@theodesp I was able to reproduce following @rrmesquita steps and disabling JavaScript in my browser. I only see the content if JavaScript is enabled which means this is not doing a Server Side Render but rather a client side render

**Comment by rrmesquita** [comment]
@jasonbahl @theodesp do you have any ideas on where I can take a look to help investigate this? I'm beginning a mid-size project, and getting this to work would be very useful.

**Comment by theodesp** [comment]
@rrmesquita TBH the bug is not obvious inside the `getWordPressProps` since we are returning data in the props as expected.
On the other hand, I would look into the FaustProvider code that updates the `seedQueries`
https://github.com/wpengine/faustjs/blob/canary/packages/faustwp-core/src/components/FaustProvider.tsx#L47

It could be that the use of context and useEffect would break SSR.

**Comment by rrmesquita** [comment]
Good guess, but `React.useEffect` is never executed in SSR. 

I've run some tests, and I think the problem lies in [this condition](https://github.com/wpengine/faustjs/blob/canary/packages/faustwp-core/src/components/WordPressTemplate.tsx#L291-L297). When a `query` property is available, `isPreview` equals to `false`, otherwise it equals to `null`.

That `null` return on line 296 is most certainly causing this issue.

**Comment by rrmesquita** [comment]
Two other things came on mind related to [this variable](https://github.com/wpengine/faustjs/blob/canary/packages/faustwp-core/src/components/WordPressTemplate.tsx#L190):

```ts
const [isPreview, setIsPreview] = useState<boolean | null>(
  templateQueryDataProp ? false : null,
);
```

- Why it is possible to be `null`?
- Shouldn't `__FAUST_QUERIES__` also be considered when defining its initial value?

**Comment by rrmesquita** [comment]
Any updates on this? It seems pretty severe as it deals with SEO – also, half the fix is already pointed out [here](https://github.com/wpengine/faustjs/issues/1813#issuecomment-1964550821). Thanks!

@blakewilson

**Comment by blakewilson** [comment]
Hi @rrmesquita,

I'm no longer working on the Faust.js project. @theodesp or @ChrisWiegman should be able to provide you with some information on the status of this issue though.

**Comment by rrmesquita** [comment]
That makes sense; thanks for the heads up.

**Comment by MajesticPagan** [comment]
Hello! Is there any updates on this? I'm having the same issue as well, when using `queries` SSR doesn't work.

@rrmesquita Have you found an alternative to this? Thank you!

**Comment by rrmesquita** [comment]
@MajesticPagan  I had to stick with using the default query system (template queries).

**Comment by MajesticPagan** [comment]
Sad to read that but thank you the feedback!

I hope the Faust.js team takes a look at this in the near future. It's really tiring having to change and repeat the same global query through all the files.

**Comment by alex-reid** [comment]
> It's really tiring having to change and repeat the same global query through all the files.

Agreed. It would also be nice to be able to leverage some of Apollo's caching so that it isn't necessary to say load data for a header and a footer on every page load etc.

**Comment by jasonbahl** [comment]
👋🏻 I'm experiencing this issue on acf.wpgraphql.com as well. I'm actively looking into this and hope to have a contribution to Faust in the near future.

**Comment by jasonbahl** [comment]
For my use case, this appears to be directly related to `useFaustQuery` which relies on Context Providers which only work in the browser. My plan, at least initially, is to update `useFaustQuery` to allow an additional 2nd parameter so the data can be retrieved from the static props instead of the Apollo Client.

i.e.

`useFaustQuery( MY_QUERY );` would become -> `useFaustQuery( MY_QUERY, { __FAUST_QUERIES__ } );`

If the `__FAUST_QUERIES__` are passed to `useFaustQuery` the data can be grabbed from that _instead_ of the Apollo client. If not, it would fall back to the Apollo Client as it does today. 

This would allow users to have a minimal upgrade path and remain backward compatible. 

Another option would be to introduce a different function, i.e. `getQueryResponse( MY_QUERY, { __FAUST_QUERIES__ } )` or something along those lines and user could move from `useFaustQuery` to the new method when ready.

A few ideas to explore, but ultimately what needs to happen is that the `__FAUST_QUERIES__` that are passed to the template file need to be used to access the data vs. using the Apollo client.

**Comment by jasonbahl** [comment]
Looks like this is probably deeper than `useFaustQuery` actually. Still digging into this.

**Comment by rrmesquita** [comment]
@jasonbahl have you looked into this? https://github.com/wpengine/faustjs/issues/1813#issuecomment-1964550821
