### ISSUE TITLE
Switch to new PHPCSStandards/PHP_CodeSniffer package

### ISSUE THREAD

**Issue by mindctrl** [wpengine/faustjs#1827]
The `Squizlabs/PHP_CodeSniffer` package has been deprecated. It has been forked and will be maintained under a new package at `PHPCSStandards/PHP_CodeSniffer`.

Reference: [The Future of PHP_CodeSniffer · Issue #3932 · squizlabs/PHP_CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer/issues/3932) 

**Acceptance Criteria**
- [ ] Existing squizlabs package is removed and replaced with the new one.
- [ ] Existing phpcs tests continue to pass. If failures happen after upgrading, the changes needed to make it pass should happen in the same PR.

**Comment by ChrisWiegman** [comment]
While the link here indicates that we didn't need to actually change the package name (they managed to keep the same namespace on Packagist), I did update us to versions of WPCS and phpcs that followed the changes from the original change in #1894
