### ISSUE TITLE
Bug: Refresh required upon authentication during login

### ISSUE THREAD

**Issue by TeresaGobble** [wpengine/faustjs#1829]
Authentication requires a refresh in the example project `custom-toolbar.` See the attached video for example behavior:

https://github.com/wpengine/faustjs/assets/50935135/8a62c455-07af-4c26-8577-c776f081d279

To replicate: 

1. go to `faustwp-core/src/components/Toolbar/Toolbar.tsx` and add the following console log on line 222:
2.  ` console.log('hasAuthenticatedUser', hasAuthenticatedUser);`
3. `npm i `and [npm run build](url) on canary branch
4. cd into custom-toolbar project and run `npm run dev`
5. Go to `localhost:3000` and open devtools, note that the value of `hasAuthenticatedUser` is `0`. 
6. Click the `Log In` button, note that the value stays at `0`, and that the toolbar does not show up.
7. Refresh the page and note the toolbar and the value (changed to `1`).

**Comment by matthewguywright** [comment]
I was able to fix this issue by accessing Cookies.get directly and not setting it to a variable.

**Comment by ChrisWiegman** [comment]
This is being closed as #1868 reverted its cause
