### ISSUE TITLE
Enable "Use the WordPress domain for media URLs in post content" by default

### ISSUE THREAD

**Issue by mindctrl** [wpengine/faustjs#1849]
# Description
By default, Faust does not enable the "Use the WordPress domain for media URLs in post content" setting. For most use cases, this causes images in post content to be broken on the front end, until the setting is enabled.

Since we seek to have a good default experience, we want to enable this setting by default so that media loads from the WP site by default.

Consideration should be given to how we achieve this without it causing the setting to enabled on existing sites where the admin may have disabled it on purpose.

**Comment by ChrisWiegman** [comment]
Completed with #1879
