### ISSUE TITLE
Faust npx creator using old versions of Faust and its dependencies

### ISSUE THREAD

**Issue by ChrisWiegman** [wpengine/faustjs#1856]
When running the Quick Start command from https://faustjs.org/tutorial/get-started-with-faust the dependencies installed are quite old. This ticket is to update this as much as possible so that folks are using the current version of Faust.

![Image](https://github.com/wpengine/faustjs/assets/394675/a17e5aac-dbe4-4b6a-93f5-8f03ec1dda56)

The screenshot above shows a list of all the dependencies installed by the npx command.

**Comment by mindctrl** [comment]
This happens due to `main` not being up to date with `canary` at the moment.

**Comment by theodesp** [comment]
I've updated the faust.js org site to mention canary branch.
