### ISSUE TITLE
Apollo error when loading CoreCode block from @faustwp/blocks

### ISSUE THREAD

**Issue by strada-jeff** [wpengine/faustjs#1870]
### Description

Getting the following error after a Wordpress update:

ApolloError: Cannot query field "content" on type "CoreCodeAttributes"

### Steps to reproduce

Loading the @faustwp/blocks in the manner outlined in the 'block-support' [example](https://github.com/wpengine/faustjs/tree/002687fafd0589d718c3d4fa3403b9ff2a3bb88c/examples/next/block-support).

After the latest Wordpress update I started getting Apollo errors like the following:

`ApolloError: Cannot query field "content" on type "CoreCodeAttributes".`

### @faustwp/core Version

3.0.1

### @faustwp/cli Version

3.0.1

### FaustWP Plugin Version

1.2.3 

### WordPress Version

6.5

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

**Comment by theodesp** [comment]
Hey @strada-jeff It looks like its related to this issue:

https://github.com/wpengine/wp-graphql-content-blocks/issues/225

apparently there is a new type `rich-text` that is not documented anywhere in the block.json spec

**Comment by theodesp** [comment]
https://github.com/wpengine/wp-graphql-content-blocks/pull/229

**Comment by theodesp** [comment]
Hey @strada-jeff this is fixed now on the latest wp-graphql-content-blocks plugin https://github.com/wpengine/wp-graphql-content-blocks/releases/tag/v4.0.0
