### ISSUE TITLE
TextArea control not working

### ISSUE THREAD

**Issue by jan-clockworkwp** [wpengine/faustjs#1895]
### Description

I wonder if anyone is able to use TextAreaControl within the custom block. TextControl works fine, richText as well, but I was not able to make TextAreaControl work. I have followed steps from the [official docs](https://faustjs.org/tutorial/react-components-to-gutenberg-blocks) as well went through the https://github.com/wpengine/faustjs/issues/1522 and tried various combinations of `block.json` and `editorFields` config. When `control: 'textarea'` is set in `editorFields` config, no matter what type is set in the `block.json` file `type: string | array | object` text area field is not being rendered at all. 

### Steps to reproduce

1. Clone `block-support` repo
2. Add another attribute with whatever name to the `block.json`, for example `message_area`
4. In `Component.js` update `editorFields` config and set `control: 'textarea'` to the newly added field `message_area`
5. Build block and review in the WP admin

### @faustwp/core Version

3.0.1

### @faustwp/cli Version

3.0.1

### FaustWP Plugin Version

1.3.1

### WordPress Version

6.5.2

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

**Comment by theodesp** [comment]
Hello @jan-clockworkwp. Thank you for the report. It looks like we are indeed missing the handler to render the `      control: 'textarea'` when you define the `Component.config.editorFields`.

We will provide a small PR soon that provides this functionality.

**Comment by theodesp** [comment]
@jan-clockworkwp @faustwp/block-editor-utils@0.2.1 contains a fix for this issue. I'm closing this ticket, but feel free to comment back if you still have any problems.

**Comment by jan-clockworkwp** [comment]
@theodesp I have tested this fix and after updating to `@faustwp/block-editor-utils@0.2.1`, `control: 'textarea'` works as expected. Thank you!

**Comment by jan-clockworkwp** [comment]
Hi @theodesp, there is one thing I have originally missed and it is the fact that if you use for textarea control type: "object" in the block.json file as described in the [faust.js docs](https://faustjs.org/tutorial/react-components-to-gutenberg-blocks), you end up with extra double quotes on the FE causing "Attempt Block Recovery" action in the backend. If you use type "string" in `block.json` file, all works as expected.
