### ISSUE TITLE
Preview detection via query string is too greedy and catches non WP previews

### ISSUE THREAD

**Issue by ccorda** [wpengine/faustjs#1903]
### Description

We're implementing a one trust cookie manager that has preview links that look like this:
`?otreset=true&otpreview=true&otgeo=`

Faust is incorrectly assuming this is a WP preview link, and redirecting logged out users to the WP admin.

This is the code where this is happening:
https://github.com/wpengine/faustjs/blob/canary/packages/faustwp-core/src/components/WordPressTemplate.tsx#L207

### Steps to reproduce

Add `?otpreview=true` to any url, e.g. `https://faustjs.org/?otpreview=true`

### @faustwp/core Version

1.2.1

### @faustwp/cli Version

1.2.1

### FaustWP Plugin Version

1.2.1

### WordPress Version

5.3

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

**Comment by theodesp** [comment]
@ccorda the latest @faustwp/core@3.0.3 version contains a fix for this issue. I'm closing this ticket but feel free to comment back if you still any problems.
