### ISSUE TITLE
recent Dependency updates might be a breaking change?

### ISSUE THREAD

**Issue by jasonbahl** [wpengine/faustjs#1941]
### Description

The changes made in https://github.com/wpengine/faustjs/pull/1929 _might_ be considered a breaking change as projects that use faust might now break until they install dependencies. 

Need to verify this, but I think some packages such as `glob` and `glob-promise` are being used by faust packages but are no longer dependencies when they maybe should be?

### Steps to reproduce

1. Take an existing project using Faust
2. update to use the latest faust (using yarn link)
3. try and build the project and see what dependencies are now required when they weren't required before

### @faustwp/core Version

canary

### @faustwp/cli Version

3.0.2

### FaustWP Plugin Version

n/a

### WordPress Version

n/a

### Additional environment details

n/a

### Please confirm that you have searched existing issues in the repo.

- [X] Yes

**Comment by josephfusco** [comment]
Note that this should be considered before merging https://github.com/wpengine/faustjs/pull/1928

**Comment by josephfusco** [comment]
This was fixed by https://github.com/wpengine/faustjs/pull/1939
