### ISSUE TITLE
Update Faust.js release workflow to upload zip to GitHub releases

### ISSUE THREAD

**Issue by josephfusco** [wpengine/faustjs#1973]
This task is intended to clean up the release workflow of the Faust.js WordPress plugin (faustwp), by having the built plugin artifact be uploaded as a release on GitHub.

**Comment by Siphompeks** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by josephfusco** [comment]
Closed by https://github.com/wpengine/faustjs/pull/1974

**Comment by josephfusco** [comment]
We will want to add a built zip to this existing release so that non-WPE customers can have access.

https://github.com/wpengine/faustjs/releases/tag/%40faustwp%2Fwordpress-plugin%401.5.0

![Image](https://github.com/user-attachments/assets/bfaeb33f-9ade-4faf-90d3-2aa61e39b11b)

**Comment by josephfusco** [comment]
The latest built zip from 1.5.0 has been added to the existing release https://github.com/wpengine/faustjs/releases/tag/%40faustwp%2Fwordpress-plugin%401.5.0
