### ISSUE TITLE
Archive legacy packages and examples in new branch

### ISSUE THREAD

**Issue by josephfusco** [wpengine/faustjs#1984]
As a faust.js maintainer, I want to remove any deprecated/unused areas of the codebase in order to clean up the codebase.

## Acceptance Criteria

- [x] A new branch `archive-legacy` exists, with legacy code for future reference
- [x] Legacy site is no longer live, with a redirect pointing to a new page on faustjs.org, stating that the legacy markdown documentation can be viewed in the repo on the `archive-legacy` branch
  - [x] New Faustjs.org `/legacy` route that provides info on where to find docs and the state of the legacy versions - https://faustjs.org/legacy this has been done on the new site and the current version
  - [x] Redirect `legacy.faustjs.org` to new `faustjs.org/legacy` page.
- [x] #1988

**Comment by josephfusco** [comment]
Given the security issues are in the example projects, it seems we can still push the older examples into a new branch, but leaving the legacy packages in place in canary for now, updating the legacy docs to point towards the legacy branch. 🤔 

![Image](https://github.com/user-attachments/assets/fcb578d9-77b4-490e-b0b7-9c41ed3859f5)

**Comment by moonmeister** [comment]
@diarmuidie Do you know who/how we can get DNS changes for `legacy.faustjs.org`?

**Comment by josephfusco** [comment]
Note that this will resolve https://github.com/wpengine/faustjs/pull/1953

**Comment by josephfusco** [comment]
We will want to verify that this is completed and that #1953 is no longer in the primary branch

**Comment by josephfusco** [comment]
Confirming that https://github.com/wpengine/faustjs/pull/1953 is no longer an issue
