### ISSUE TITLE
[PROPOSAL] Authentication and authorization requirements

### ISSUE THREAD

**Issue by wjohnsto** [wpengine/faustjs#214]
This is a reference to #198 which discusses:

> - Authentication and authorization
>   - OAuth handlers
>   - JWT Auth

## Auth Implementation
There is currently a limited implementation of auth in `core` and the WordPress plugin. Here is how OAuth should work, including suggestions for how `core` should handle authorization and authentication:

> **NOTE**: Some of these features may already exist

- The `WordPress plugin` should publish a route where you can send a user to have them authenticate with WordPress
- Upon successful login, the `WordPress plugin` will generate a short-lived Authorization Code and redirect the user to a specified redirect URL on the frontend
- The `frontend server` should use the Authorization Code and the configured secret key to exchange the code for an access token and refresh token (and associated expirations)
- The `frontend server` should store the access token and refresh token in a client-side cookie to be used with subsequent requests to WordPress
- The `WordPress plugin` should provide a WPGraphQL mutation that allows exchanging an Access Token and Refresh Token for a new Access Token and Refresh Token
- The `WordPress plugin` should provide a WPGraphQL mutation that allows exchanging a username and password for an Access Token and Refresh Token
- `core` should handle access token expiration by automatically requesting a new set of tokens when the access token is soon to expire
- `core` should provide functionality for:
  - logging in with username and password
  - exchanging refreshing tokens
  - exchanging authorization code and secret for tokens
  - logging out (clearing cookie)

## Access Token and Refresh Token Generation

Currently the `WordPress plugin` only generates an access token with no expiration. We should move to generating both an access token and a refresh token. Here are my suggestions for default token expirations:

- Access token expiration: 180 days
- Refresh token expiration: 1 year

> **NOTE**: These expirations should be configurable in the WordPress plugin

## Secret Key Generation

Currently the `WordPress plugin` automatically generates a secret key using `wp_generate_uuid4`. You are also able to regenerate the key when needed. Should this functionality remain the same? Some plugins (such as [WPGraphQL JWT Auth](https://www.wpgraphql.com/extenstion-plugins/wpgraphql-jwt-authentication/)) seem to require a developer to define a secret, and provide no menu functionality to automatically generate one. The benefit of doing it the way JWT Auth does it is you don't run the risk of a publisher accessing the menu and accidentally regenerating the key.

**Comment by matt-landers** [comment]
This is how I envisioned auth working as well. Having JWT auth baked in is ideal so that the mechanism is shared between the 2 methods. We should allow for JWT and OAuth to be enabled individually. Ideally, you won't have the login mutation unless you need it.

For the secret, I'd rather it stay in the settings panel. Needing to edit PHP is not ideal for a headless developer. We can do an authorization check in order to regenerate and only allow admins if that becomes a problem.

**Comment by blakewilson** [comment]
I agree I think this auth flow works nicely! One thing we may want to consider is to have the access token's expiration default to a value more short-lived. In the case a user's access token is misplaced or stolen, that account could be vulnerable up to 180 days with the only way to invalid the token being to change the secret.

In terms of secret generation I agree with @matt-landers that it should stay in the settings panel. But we could also look for a constant in `wp-config.php` that would supercede the settings menu value. If the constant is found in `wp-config.php`, the settings menu field would be disabled. Some developers may prefer their `env` variables hard coded. I've seen this in the [WooCommerce API Manager](https://woocommerce.com/products/woocommerce-api-manager/) plugin and it works well.

**Comment by kaelri** [comment]
@blakewilson That's a good idea. As a developer, I also prefer to store environment variables in `wp-config` for safety reasons: it keeps them out of the database, and ensures that when a WP site is mirrored between environments (prod/stage/dev/local), secrets and credentials don't come along for the ride. A database setting superseded by a PHP constant sounds ideal.
