### ISSUE TITLE
Next Cache-Control Headers

### ISSUE THREAD

**Issue by matt-landers** [wpengine/faustjs#230]
By default, Next sets `max-age=0` on the `cache-control` headers. This is not ideal in a production app. The headers can be manipulated via `next.config.js` https://nextjs.org/docs/api-reference/next.config.js/headers.

The framework should set a reasonable default and allow for some level of configuration.

**Comment by wjohnsto** [comment]
Maybe a guide for this, since the framework doesn't require any next.config.js so it might not be the best idea to require a custom config just for something you can do on your own.

**Comment by blakewilson** [comment]
It looks like Next has changed the way the `Cache-Control` header is applied since the issue was originally opened:

> Cache-Control headers set in next.config.js will be overwritten in production to ensure that static assets can be cached effectively. If you need to revalidate the cache of a page that has been statically generated, you can do so by setting revalidate in the page's getStaticProps function.

https://nextjs.org/docs/api-reference/next.config.js/headers#cache-control
