### ISSUE TITLE
[wpe-headless] Site URL conflict

### ISSUE THREAD

**Issue by moonmeister** [wpengine/faustjs#233]
Hey All, I just ran across a "bug" and I'm not sure who needs to know so thought I'd send it to both of you. So yesterday I changed the "Site Address (URL)" to point to my atlas front end. ~~this fixed all the "View" buttons for posts and pages.~~ It fixes an issue in wpgraphql I talked with Jason on the other day where the `nodeByUri` uses the `site_url`. 

HOWEVER, once this is changed Gutenberg is broken. For some reason Gutenberg uses the frontend url and it breaks the ability to create/update posts. There are some solutions @ https://github.com/WordPress/gutenberg/issues/1761 .

![image](https://user-images.githubusercontent.com/2730871/119007958-909d2880-b946-11eb-92f3-fe86759c1eb0.png)

**Comment by wjohnsto** [comment]
This is an issue I have run into, and I believe it is why the plugin operates separately from the Site Address and overwrites View buttons on it's own.

Correct me if I'm wrong @mindctrl!

**Comment by moonmeister** [comment]
Yup, this was already pointed out in the pr. Sorry if I over explained anything in my response there.
