### ISSUE TITLE
Proposal: Menus

### ISSUE THREAD

**Issue by moonmeister** [wpengine/faustjs#292]
## Overview
I was working on implementing dynamic menus driven by WP for a couple example sites and thought it'd be helpful to have some React hooks for fetching data. This could also be a great area for creating reusable components. Menus aren't terribly hard but can get more complicated when you start thinking about accessibility and nesting.

## The Query
So there's 2 ways to fetch menu item nodes in WPGraphQL we could use for fetching menu data. 

### Menu

First we can query by menu:

```graphql 
query MainMenu {
  menu(id: "Main" idType: NAME){
    menuItems {
      nodes {
        label
        path
      }
    }
  }
}
```
This is nice but ignores a key functionality of WP, menu locations.

From what I've seen, menu locations are the preferred way to hook into menus in WP because they enable WP to control and change which menus show up where.

### MenuItems
In that spirit I've taken to using the second method of fetching menu data:

```graphql
query PrimaryMenu{
  menuItems(where: {location: PRIMARY}) {
    nodes {
      label
      path
    }
  }
}
```

This query is a little simpler in addition to the previously mentioned benefits. One of the downsides though is not being able to fetch and data about the menu itself: `count`, `isRestricted`, `name`, `slug`, `databaseId`, `id`, `locations`. 

While I have never needed any of these fields they exist for a reason and could be reasonably desired. Maybe this isn't our problem and we just implement 1 or both hooks and let folks use them as desired. 

### Menu Alt
For the sake of completeness, I'll suggest a 3rd method that would be best of both worlds but would require a new feature. 

```graphql
query PrimaryMenu {
  menu(id: PRIMARY idType: LOCATION){
    count
    menuItems {
      nodes {
        label
        path
      }
    }
  }
}
```

I assume this is possible technically and just hasn't been implemented. It allows accessing all possible data and use of the WP Location feature.

## The Hook

The actual naming convention of the hook would be respective to the data type being queried 

```javascript

const { menuItems } = useMenu("Main")

// or 

 const menuItems = useMenuItems('PRIMARY')

// or

const { menuItems, count } = useMenu('PRIMARY')

// or 

const { menuItems, count } = useMenu({id: 'PRIMARY', idType: 'LOCATION' })
```

# The Nested Menus

Nested menus (aka recursion) get's a little funny but is not the end of the world. I will say I'm not sure what gqless can do, I'll provide solutions I've seen.

Both query formats discussed previously return all menu items, regardless of depth. Using the `parentId` field we can use JS to create any desired data structure and render components. 

thanks to @wjohnsto for thinking through some of the options with me.

**Comment by blakewilson** [comment]
Hey @moonmeister!

Thanks for writing up this proposal. I think some kind of menu hook is definitely needed.

I like the idea of querying a menu by location. It feels familiar to how themes are currently developed in PHP. However, A possible downsides I see is that WordPress menu locations are defined in the theme itself. In a Headless site, there may be a disconnect there.

I think your first example where menus are queried by `id` and `idType` would offer the most functionality. This closely reflects how our hooks currently work. In the framework, this could look like:

```tsx
const menu = useMenu({
  id: 'My Menu',
  idType: MenuNodeIdTypeEnum.NAME,
});
```

As you mentioned before, this would allow the user to use menu related properties like `count`, `name`, `slug`, `locations`, etc, as well as access the menu items.

A `useMenu` hook could then be used alongside `menuItems`/`childItems` to create a menu with proper nesting. Something like:

```tsx
// nav.tsx

import Link from 'next/link';
import { client } from '@wpengine/headless-next';
import { MenuItem, MenuNodeIdTypeEnum } from '@wpengine/headless-core';

interface MenuItemProps {
  menuItem: MenuItem;
}

function Item({ menuItem }: MenuItemProps) {
  if (!menuItem?.url) {
    return null;
  }

  return (
    <li>
      <Link href={menuItem?.url}>
        <a>{menuItem?.label}</a>
      </Link>

      {menuItem?.childItems()?.nodes.length > 0 && (
        <ul>
          {menuItem?.childItems()?.nodes.map((childItem) => (
            <Item key={childItem.id} menuItem={childItem} />
          ))}
        </ul>
      )}
    </li>
  );
}

export function Nav() {
  const { useMenu } = client();

  const menu = useMenu({
    id: 'My Menu',
    idType: MenuNodeIdTypeEnum.NAME,
  });

  const menuItems = menu?.menuItems()?.nodes;

  return (
    <nav>
      <h2>{menu?.name}</h2>
      <ul>
        {menuItems
          ?.filter((menuItem) => menuItem?.parentId == null)
          .map((menuItem) => (
            <Item key={menuItem.id} menuItem={menuItem} />
          ))}
      </ul>
    </nav>
  );
}
```

This is a basic example, but it demonstrates how a user could want to display their menu items.

Something to note that I just came across in WP GraphQL: a menu is only accessible publicly if it is set to a location. That means you couldn't just create a menu, then reference it in `useMenu`. You would first have to set it to a location. This can be frustrating if the user doesn't realize this is a constraint.

@moonmeister @wjohnsto Thoughts?

**Comment by moonmeister** [comment]
@blakewilson thanks for adding your thoughts. 

Good reminder of the location is required for a menu to be public. I had forgotten that. Imo that reinforces my desire to fetch by location cause it avoids a pitfall by requiring the location to be set. 

Also, the headless plugin already creates locations by default. I think locations are kinda like a custom field schema. It's a contract between developers and designers. Menus and their names may come and go but the location is constant and typed. 

Side note, I'm being pedantic here so feel free to ignore but I ran into this yesterday so I'll point it out. You probably want to use the `path` attribute from `menuItems` as on internal links it doesn't contain the domain. External links remain complete. `url` always an absolute link.

**Comment by wjohnsto** [comment]
Another interesting thing about the WPGraphQL menu fetching (though I don't know how much it matters): You can only get a menu by name/location if it has items.

**Comment by moonmeister** [comment]
🤔 @jasonbahl Any input here?
