### ISSUE TITLE
Enhancements to Authentication

### ISSUE THREAD

**Issue by wjohnsto** [wpengine/faustjs#293]
There has been a lot of talk about how difficult authentication is to get setup with Headless WordPress. Currently the framework mostly supports authentication for previews only. It doesn't make it easier for someone who:

- Wants to password protect their frontend
- Wants a login page on their frontend site
- Desires high security with minimal implementation complexity

For the above reasons there are a few enhancements we can make to the framework that will support multiple different authentication needs. We can accomplish this without having to rewrite our current authentication code, but by simply adding a few things.

1. The WordPress plugin will support it's current functionality of redirect-based logging in and obtaining authorization codes
1. The WordPress plugin will publish a `WPGraphQL` mutation for exchanging a username/password for an authorization code
    - This will prevent access tokens from ever being exposed from WordPress to a client
1. The WordPress plugin will publish an API route to exchange an `authorization code` or `refresh token` and a `client secret` for tokens
    - Instead of simply returning an access token the framework you return the following values
    - `Access token`: short-lived, used for authenticated requests
    - `Access token expiration`: a datetime indicating when the access token will expire
    - `Refresh token`: a longer-lived token, used to get a new access token and refresh token
    - `Refresh token expiration`: a datetime indicating when the refresh token will expire
1. `core` will use first-party cookies to store tokens (we are already doing this). This will be the most future-proof way to handle authentication.
    - The `refresh token` will be stored in an `httpOnly`, `secure`, `SameSite=strict` cookie
    - The `access token` will never be stored in a cookie, it will be used on the frontend in-memory
1. `core` will publish an API middleware function for exchanging an `authorization code` for tokens using the redirect scheme
    - This is what the current `authorizeHandler` middleware function accomplishes
1. `core` will publish and API middleware function for getting new tokens without redirecting
    - This middleware will support passing an `authorization code` in a query param
    - If no `authorization code` exists the middleware will check for a `refresh token` and use it if it exists
    - If no `authorization code` or `refresh token` exists the middleware will respond with a 401 Unauthorized error
    - Upon successfully obtaining new tokens from WordPress this middleware will store the new `refresh token` in cookies and respond with the new `access token`
1. `core` will publish a client function for logging in using a username/password
    - This function will use the WPGraphQL mutation to exchange a username/password for `authorization code`
1. `core` will allow for configuring authentication scheme to be used, which will support the following values:
    - `redirect` means `core` will assume authentication is initialized through redirecting to the WP login page
    - `local` means `core` will assume authentication is initialized through username/password login
1. `core` will allow for configuring an optional route for a local login page
1. `core` will publish a client function for exchanging an optional `authorization code` for an access token
    - This function will call the API middleware and pass the `authorization code` if it exists
    - If this function receives a 401 from the API middleware it will determine next steps based on the authentication scheme
        - For `redirect` this function will redirect to WordPress to login
        - For `local` this function will redirect to the configured route for the local login page

**Comment by blakewilson** [comment]
Posting this here for a visual representation of the local login flow:
![Local Login Authentication Flow](https://user-images.githubusercontent.com/5946219/127883740-853bea66-da41-4ff4-8432-08e80e592754.png)

**Comment by wjohnsto** [comment]
This should end up in an authentication guide in our docs.

**Comment by blakewilson** [comment]
Updated authentication flows documenting the client secret:

![Local Login Authentication Flow](https://user-images.githubusercontent.com/5946219/130268550-d47baf8e-c1f6-4f02-bc3a-febac5c0ae63.png)
![Redirect Login Authentication Flow](https://user-images.githubusercontent.com/5946219/130268555-39805a72-5329-4bac-85fb-3c79321fdb26.png)
