### ISSUE TITLE
wpe-headless plugin triggers PHP notice on WP 5.8 widgets screen

### ISSUE THREAD

**Issue by mindctrl** [wpengine/faustjs#354]
Steps to reproduce, with the `wpe-headless` plugin active:

- Visit Appearance > Widgets in wp-admin (`/wp-admin/widgets.php`)
- See PHP notices being triggered

Notice text:
> PHP Notice:  wp_enqueue_script() was called <strong>incorrectly</strong>. "wp-editor" script should not be enqueued together with the new widgets editor (wp-edit-widgets or wp-customize-widgets). Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 5.8.0.)

This appears to be happening because of the `previewlinks.js` file being loaded here: https://github.com/wpengine/headless-framework/blob/a99ce09d96fc0e9c47b0b9f2dc43301518196609/plugins/wpe-headless/includes/replacement/callbacks.php#L215

It appears the `wp-edit-post` script causes `wp-editor` to load too. Commenting out this code results in the error going away.

A fix might be to scope the loading of this script to the `load-post-new.php` and `load-post.php` hooks, or something similar that only loads the script on the post editor screens where it's being used.

**Comment by blakewilson** [comment]
Closed via #429
