### ISSUE TITLE
Is it possible to use Headless Framework without gqless and Apollo?

### ISSUE THREAD

**Issue by krishaamer** [wpengine/faustjs#362]
For example, can I just be very basic and use fetchAPI to access the WP GraphQL endpoint? Or is gqless a prerequisite to using the Headless Framework? Thanks.

**Comment by wjohnsto** [comment]
I'm not sure you would want to use this framework without `gqless` given that the primary functionality of the framework currently revolves around helping you get data from WordPress using `gqless`. If you want to use `fetch` alone I would recommend using a basic Next starter.

**Comment by krishaamer** [comment]
Thanks for the clarification. I'm still trying to figure out if gqless is workable for my projects. I've hit a few roadblocks on my first day trying to rewrite an existing headless WP/Next site. For example when building a multilevel menu I previously could check if the menu item has children by checking the length of the children's node. However I can't see a way to do that with gqless as it will always return 0 even if there are children. Am I doing this wrong or does gqless sometimes miss some data we could previously access with fetch?

`query MyMenu {
  menus {
    nodes {
      menuItems(where: {location: PRIMARY}) {
        edges {
          node {
            label
            url
            id
            childItems {
              edges {
                node {
                  title
                  url
                }
              }
            }
          }
        }
      }
    }
  }
}
`


`import { Disclosure, Menu, Transition } from "@headlessui/react";
import Link from "next/link";
import useTranslation from "next-translate/useTranslation";
import { client, MenuLocationEnum } from "client";

function normalizedRelativeURL(link: any) {
  let url = "/";
  if (link?.url && link?.url !== "#") {
    url = link?.connectedNode ? new URL(link?.url).pathname : link?.url;
  }

  return url;
}

export default function MainMenu() {
  const { t } = useTranslation("common");
  const { useQuery } = client;

  const links = useQuery().menuItems({
    where: { location: MenuLocationEnum.PRIMARY },
  }).nodes;

  return (
    <Disclosure as="nav" className="bg-black">
      {({ open }) => (
        <>
          <div className="max-w-7xl mx-auto">
            <div className="relative flex items-center justify-between h-16">
              <div className="absolute inset-y-0 left-0 flex items-center sm:hidden">
                <Disclosure.Button className="text-white inline-flex items-center justify-center ml-4">
                  {open ? "X" : t("menu")}
                </Disclosure.Button>
              </div>

              <div className="flex-1 flex items-center justify-center">
                <div className="hidden sm:block sm:ml-20">
                  <div className="flex space-x-4">
                    {links?.map((link, i) => {

                      console.log(link?.childItems?.length);

                      if (link?.childItems?.length) {
                        return (
                          <a className="text-red uppercase">KID</a>
                        );
                      } else {
                        return (
                          <Link
                            href={normalizedRelativeURL(link) ?? ""}
                            key={link?.id ?? "empty_" + i}
                          >
                            <a className="text-white uppercase">
                              {link?.label}
                            </a>
                          </Link>
                        );
                      }
                    })}
                  </div>
                </div>
              </div>
            </div>
          </div>

          <Disclosure.Panel className="sm:hidden">
            <div className="px-2 pt-2 pb-3 space-y-1">
              {links?.map((link, i) => {
 
                return (
                  <Link href={normalizedRelativeURL(link) ?? ""} key={link?.id ?? "empty_" + i}>
                    <a className="text-white uppercase block px-3 py-2 text-base font-medium">
                      {link?.label}
                    </a>
                  </Link>
                );
              })}
            </div>
          </Disclosure.Panel>
        </>
      )}
    </Disclosure>
  );
}
`

**Comment by wjohnsto** [comment]
I see you are logging `link?.childItems?.length` but I believe what you're looking for is `link?.childItems?.edges?.length` or `link?.childItems?.nodes?.length` since `childItems` is a connection and the `nodes` and `edges` properties will be arrays.
