### ISSUE TITLE
Rename repo from headless-framework to faustjs

### ISSUE THREAD

**Issue by wjohnsto** [wpengine/faustjs#408]
Let's compile a list of areas where we need to change links, then we can give the go-ahead.

**Comment by wjohnsto** [comment]
[Relevant search in the framework](https://github.com/wpengine/headless-framework/search?q=headless-framework)
[Relevant search in the docs](https://github.com/wpengine/headless-docs/search?q=headless-framework)

**Comment by blakewilson** [comment]
Off the top of my head outside of the repo:

* YouTube Videos / Descriptions
* DE{CODE} Podcast metadata

Also, we should still have redirects in place for `wpengine/headless-framework` -> `wpengine/faustjs` as long as a new `headless-framework` repo is not created:
https://github.community/t/how-long-does-github-forward-renamed-moved-repos/582/3

**Comment by wjohnsto** [comment]
I didn't find any podcast metadata linking directly to the framework repo, so we should be fine there.

**Comment by mindctrl** [comment]
Some other repos in the wpengine org use this repo, and redirects probably work fine, but it'd be good to notify them I think so they can update their code, because if someone does create a new repo with the same name their builds will break: https://github.com/search?q=org%3Awpengine+headless-framework&type=code

**Comment by wjohnsto** [comment]
Once we change the name I will notify the relevant repo maintainers

**Comment by blakewilson** [comment]
An issue I just came across: The Local Atlas extension has an option to create a headless frontend. Right now it references the `wpengine/headless-framework` and fails. I'm working on a fix for this right now.

**Comment by wjohnsto** [comment]
> 
> 
> An issue I just came across: The Local Atlas extension has an option to create a headless frontend. Right now it references the `wpengine/headless-framework` and fails. I'm working on a fix for this right now.
> 
> [getflywheel/local-addon-atlas#24](https://github.com/getflywheel/local-addon-atlas/pull/24)

This looks done, now that faustjs.org is up I'll start going through the rest of the rewrites.
