### ISSUE TITLE
Bug: Existing post/page previews do not pull the latest revision

### ISSUE THREAD

**Issue by blakewilson** [wpengine/faustjs#422]
Viewing previews of existing posts/pages do not pull the latest revision. Instead, they show the published post/page content

## Applicable Versions

- `@faustjs/core` version: 0.9.0
- `@faustjs/react` version: 0.9.0
- `@faustjs/next` version: 0.9.0
- WordPress version: N/A

## Steps To Reproduce

1. Go to an existing page/post in the WordPress admin
2. Make changes
3. View Preview

## The current behavior

Upon clicking preview on an existing post or page, the user is given the most recently published content

## The expected behavior

Upon clicking preview on an existing post or page, the user is then given the most recent changes, regardless of publish status

**Comment by moonmeister** [comment]
I believe this is a Gutemberg/WP core bug. https://github.com/WordPress/gutenberg/issues/33616

**Comment by blakewilson** [comment]
@moonmeister This is due to how we were previously fetching data in our `usePreview` hook. Previously, we were querying for just the post/page content, which worked for drafts and new pages/posts, but didn't for existing. We now check if there are revisions, and if so, display that:

https://github.com/wpengine/faustjs/blob/d77273de46035503d68d6d03f92bfbff55be6c24/packages/next/src/client.ts#L305

**Comment by moonmeister** [comment]
So is this bug solved or is this bug in the new implementation?

**Comment by blakewilson** [comment]
@moonmeister Yep this is in the new implementation, still in progress, but the PR is here: #426
