### ISSUE TITLE
Investigate triggering rebuilds from WordPress

### ISSUE THREAD

**Issue by wjohnsto** [wpengine/faustjs#461]
Next.js supports time-based [Incremental Static Regeneration](https://vercel.com/docs/next.js/incremental-static-regeneration) which is nice, but it would be nicer to be able to regenerate pages/posts only when the content changes. Is there a way we can do this? If so, how can Faust.js best support it?

**Comment by blakewilson** [comment]
Closed via #469

**Comment by blakewilson** [comment]
It looks like the Next.js team is working on this functionality https://github.com/vercel/next.js/discussions/11552#discussioncomment-646963.

@leerob said he'd post an update in the thread when there is more to share (https://github.com/vercel/next.js/discussions/11552#discussioncomment-989514)

**Comment by leerob** [comment]
Indeed! Super excited about this feature.

**Comment by wjohnsto** [comment]
Awesome, let's keep an eye on this so we have something ready day 1.

**Comment by blakewilson** [comment]
Next.js Conf is happening Oct 26. Maybe we'll see this feature announced then? 🤔 

https://nextjs.org/conf

**Comment by blakewilson** [comment]
On-demand ISR just landed in Next.js 12.1 🎉 

https://github.com/vercel/next.js/discussions/11552#discussioncomment-2198169

Nice @leerob!
