### ISSUE TITLE
Bug: `conditionalTags` returns `false` if slug not included in the query. 

### ISSUE THREAD

**Issue by justlevine** [wpengine/faustjs#477]
Running into weird behavior using `conditionalTags`. On the backend, it seems to only work if the slug is included in the query (or a previous one for some reason). Unclear if this affects `gqty` calls on the frontend (I'm trying to debug a catch-all route, and this is where I got stuck).

![image](https://user-images.githubusercontent.com/29322304/133641972-50753e3e-d79e-4ce1-9836-afa00ef6b3b8.png)

## Applicable Versions

- `@faustjs/core` version: 0.10.2
- `@faustjs/react` version: 0.10.2
- `@faustjs/next` version: 0.10.2
- WordPress version: 5.8.1
- WPGraphQL version: 1.6.4
- WPE-Headless Plugin version: 0.6.0

## Steps To Reproduce

1. Install and activate WPE-Headless plugin and WPGraphQL, and visit WPGraphIQL on the backend.
2. Copy and run the following query:
```graphql
{
  categories(first: 1) {
    withoutSlug: nodes { # All tags will return false.
      conditionalTags {
        isArchive
        isSingular
        isCategory
        isPostTypeArchive
      }
    }
    withSlug: nodes { # Correct values will return.
      slug
      conditionalTags {
        isArchive
        isSingular
        isCategory
        isPostTypeArchive
      }
    }
    withoutAgain: nodes { # Correct values will return, since slug was included earlier.
      conditionalTags {
        isArchive
        isSingular
        isCategory
        isPostTypeArchive
      }
    }
  }
}

```

## The current behavior
All `conditionalTags` fields return `false`, unless slug was included (previously) in the query.

## The expected behavior
Shouldn't need to include anything but `conditionalTags` for the fields to resolve correctly.

**Comment by blakewilson** [comment]
Hey @justlevine, thanks for reporting this!

`conditionalTags` were introduced in the old version of the framework when routing was done from the [`NextTemplateLoader`](https://github.com/wpengine/faustjs/blob/9fff5cb507c35f3e6297fea23595e1efbf410d3c/examples/getting-started/pages/%5B%5B...page%5D%5D.tsx#L16). Now that we are using [Next.js pages](https://nextjs.org/docs/basic-features/pages) for routing, `conditionalTags` are no longer needed.

Could you describe your use case for `conditionalTags`? Maybe we could support your use case without them.

**Comment by justlevine** [comment]
I'm trying to create next.js routes that can mimic Wordpress' flexible permalinks. Eg. `{postType}\{taxonomyTerm}\{...childTaxonomyTerm}\{postSlug}`. Because WPGraphQL places this information in different places on the node, having consistently-placed conditionalTags would be very helpful in determining whether to render for example an Archive.tsx or a Post.tsx component.

**Comment by josephfusco** [comment]
Closing as ConditionalTags was deprecated in #755
