### ISSUE TITLE
Bug: Lint errors with `next build` (`npm run build`) for the `next/getting-started`

### ISSUE THREAD

**Issue by wjohnsto** [wpengine/faustjs#483]
## Applicable Versions

- `@faustjs/core` version: 0.10.2
- `@faustjs/react` version: 0.10.2
- `@faustjs/next` version: 0.10.2
- WordPress version: N/A

## Steps To Reproduce

1. Follow the [instructions on faustjs.org for getting started](https://faustjs.org/docs/next/getting-started) 
2. Run `npm run build`
3. The following lint error will show up

![next/document should not be imported outside of pages/_document.js](https://user-images.githubusercontent.com/785258/133806349-8ce8558e-c44b-463d-9d0f-3dec4b327aed.png)

The easiest way to fix this is to ignore it, but I think this is actually a bug in Next's lint rule. According to [this doc](https://nextjs.org/docs/messages/no-document-import-in-page) it should work with `pages/_document.tsx`... maybe the issue is we're using a `src` directory?

**Comment by blakewilson** [comment]
Looks like this was acknowledged in https://github.com/vercel/next.js/issues/29021#issuecomment-922328229 and there is a fix out in canary. We should see this resolved in Next `11.1.3`
