### ISSUE TITLE
Create `useContentNode` hook that will work for posts or pages (or other content types potentially)

### ISSUE THREAD

**Issue by wjohnsto** [wpengine/faustjs#514]
Let's see how we can support a single URI for (at least) posts and pages now that we have GQty@2 with the `$on` Unions.

The WPGraphQL `contentNode` query allows you to make multiple Union queries, including custom content types. We should be able to provide some functionality around that.

**Comment by wjohnsto** [comment]
This should satisfy, or is a least related to bug #510

**Comment by josephfusco** [comment]
Closing for now. Will discuss in future planning.
