### ISSUE TITLE
Consider renaming the `src/pages/api/auth/wpe-headless.ts` endpoint

### ISSUE THREAD

**Issue by blakewilson** [wpengine/faustjs#518]
Currently, the Next.js auth middleware is called `src/pages/api/auth/wpe-headless.ts`. We should consider renaming this to something more related to auth, perhaps: `src/pages/api/auth/authorize.ts`

**Comment by wjohnsto** [comment]
Thinking more on this, we might want to instead provide a single entry point for multiple potential API endpoints. So something like

`src/pages/api/faust/[[...route]].ts` could be an entry point for multiple API routes, and we can manage it internally.

**Comment by blakewilson** [comment]
@wjohnsto I like this idea. This will make things much more maintainable
