### ISSUE TITLE
Update Custom Post Type guide demonstrating how to create single pages

### ISSUE THREAD

**Issue by blakewilson** [wpengine/faustjs#544]
The [Custom Post Types guide](https://faustjs.org/docs/next/guides/custom-post-types) should demonstrate how to create single pages for each custom post type post

This is waiting on the completion of #619

**Comment by chrishale** [comment]
@blakewilson For me #716 doesn't document this, or at least I'm failing to understand the concept. I can't work out how to create a template that fetches a single post that is a custom post type.
