### ISSUE TITLE
Create a guide specifically for GQty

### ISSUE THREAD

**Issue by wjohnsto** [wpengine/faustjs#564]
Add a guide for GQty that goes over the basics of using GQty with Faust.js. 

- Link to this doc from the `Fetching Data" guide.
- Link to relevant docs on gqty.dev
- Try to outline the differences between Faust.js hooks and GQty
- Outline common scenarios for gqty (i.e. use in getStaticPaths, paginated queries, mutations, error handling, etc).

**Comment by blakewilson** [comment]
Closed via #652
