### ISSUE TITLE
Getting a schema generate issue when I command npm run generate

### ISSUE THREAD

**Issue by sachinnawale99** [wpengine/faustjs#576]
![Screenshot 2021-10-12 at 4 31 27 PM](https://user-images.githubusercontent.com/30441931/137086005-37ea99e1-abf4-431d-bac4-9a410c272f50.png)
Hello Everyone, I'm having a schema generate issue when I command npm run generate. That's the reason I am not able to see my custom fields.  Is that any way to solve this error? Thanks

**Comment by vaihtovirtahepo** [comment]
You can also rename .env.local to .env and that will fix the problem.

**Comment by blakewilson** [comment]
@sachinnawale99 👋 

We've smoothed over a few issues in the tutorail/getting started. The latest changes should now fix this.

**Comment by blakewilson** [comment]
This should be resolved now on the Faust.js/docs side. However, if anyone is still experiencing this, please feel free to open a new issue
