### ISSUE TITLE
Docs: The link of the example of `usePosts` with pagination is wrong.

### ISSUE THREAD

**Issue by hideokamoto** [wpengine/faustjs#583]
On this page, we can go to the example code on how to use `usePosts` with pagination.
https://faustjs.org/docs/next/reference/custom-hooks

But when clicking the link, we'll get the 404 error page.
I think we need to upgrade the repo URL on the link URL.

current: https://github.com/faustjs/framework/blob/canary/examples/next/getting-started/src/pages/posts/index.tsx#L17-L22
expected: https://github.com/wpengine/faustjs/blob/canary/examples/next/getting-started/src/pages/posts/index.tsx#L18-L23

**Comment by apmatthews** [comment]
Hi @hideokamoto 👋🏻  Thanks for the PR and for opening an issue first! It looks like this has since been fixed in #725.
