### ISSUE TITLE
The current docs do not make it clear how to use Faust.js on production on a live domain

### ISSUE THREAD

**Issue by lukecav** [wpengine/faustjs#585]
Include some information about how to go live using Faust.js on a live domain in production, not on dev.

**Comment by Saggitarie** [comment]
I'm agree with this. I'll peak into the discord channel to find for any hints.

**Comment by blakewilson** [comment]
Agreed. Some docs on how to deploy to [Atlas](https://wpengine.com/atlas/), [Vercel](https://vercel.com), [Gatsby](https://www.gatsbyjs.com/), etc. would be great.

**Comment by blakewilson** [comment]
Closed via #765
