### ISSUE TITLE
Bug: contentNode $on union infinite loop

### ISSUE THREAD

**Issue by lilgujj** [wpengine/faustjs#586]
Hello! after some debugging in my code i cant find anything that would start infinite re render after installing "^0.12.0" to use $on union to fetch data. 
i followed ur guide: https://faustjs.org/docs/release-notes#faustjs-0110

related closed issue #510

## Applicable Versions

- `@faustjs/core` version: "^0.12.0"
- `@faustjs/react` version: "^0.12.0"
- `@faustjs/next` version: "^0.12.0"
- WordPress version: 5.8.1

**Comment by mediashane** [comment]
This bug is reoccurring with "@faustjs/core": "^0.14.1", "@faustjs/next": "^0.14.0", and "gqty": "^2.1.0".
