### ISSUE TITLE
SSG getStaticPaths error

### ISSUE THREAD

**Issue by lilgujj** [wpengine/faustjs#625]
Hello! When trying to use your example code to render static pages i get this error:
Error: The provided path `/` does not match the page: `/[...pageUri]`.

**code:** 

```tsx
export async function getStaticPaths() {
  const values = await client.client.inlineResolved(() => client.client.query
    .pages()
    ?.nodes?.map((node) => node?.uri));
  const paths = [];

  if (Array.isArray(values)) {
    paths.push(
      ...values
        .filter((value) => typeof value === 'string'),
    );
  }
  return {
    paths,
    fallback: 'blocking',
  };
}
```

**i use contentNodes to fetch the data that looks like this:**

```tsx
const { pageUri } = useRouter().query;

const contentNode = client.useQuery().contentNode({
  id: (pageUri as string[]).join("/"),
  idType: ContentNodeIdTypeEnum.URI,
});

const page = contentNode?.$on?.Page;

```

**getStaticProps looks like this:** 

```tsx
export async function getStaticProps(context: GetStaticPropsContext) {
  return getNextStaticProps(context, {
    Page: Slug,
    client,
    notFound: await is404(context, { client }),
  });
}
```

related issue: #616

**Comment by lilgujj** [comment]
solved this by changing:

from: 
.filter((value) => typeof value === 'string'),

to: 
.filter((value) => value !== '/'),

guess its because of [...pageUri] should not render the '/' route?  becausei have an seperate index.tsx thats only for the homepage? sorry for inconvenience :)

**Comment by blakewilson** [comment]
Hey @lilgujj, I'm glad you solved this. I'll close this issue, but if you experience further issues please feel free to open a new issue.
