### ISSUE TITLE
Bug: SyntaxError: Unexpected token '?' on ios13 and below

### ISSUE THREAD

**Issue by aquamoose** [wpengine/faustjs#648]
When running the Faust.js next/getting-started example on BrowserStack on ios13, this error occurs:

SyntaxError: Unexpected token '?'

<img width="689" alt="Screen Shot 2021-11-16 at 2 32 48 PM" src="https://user-images.githubusercontent.com/5869159/141933586-f9d14cce-a442-491e-be92-1a439f858d02.png">

## Applicable Versions

- `@faustjs/core` version: 0.13.1
- `@faustjs/react` version: 0.13.1
- `@faustjs/next` version: 0.13.1
- WordPress version: N/A
- Node Version: 15.5.1

## Steps To Reproduce

1. Use an ios version 13 and below iPhone or use BrowserStack to test on ios version 13 and below
2. [Follow the Faust.js getting started instructions](https://faustjs.org/docs/next/getting-started)
3. `npm run dev`

Link to code example:

**Comment by moonmeister** [comment]
Hey @blakewilson, I asked @aquamoose on a call to try this on an LTS version of node and confirm whether that changes anything. If you or your team has anything to add, please chime in.

**Comment by blakewilson** [comment]
@aquamoose @moonmeister Yeah please let me know if you still experience this issue on an LTS version of node. Currently we're focusing on supporting Node v14 and v16.

**Comment by blakewilson** [comment]
Going to close this for now, but please open a new issue if you continue to see this on versions v14/16 of Node
