### ISSUE TITLE
How to separate wordpress urls for CSR and SSR 

### ISSUE THREAD

**Issue by m1kit** [wpengine/faustjs#649]
Currently I am building a faust.js blog with docker compose like this:
```
docker-compose.yml
- frontend (my own image)
  - port 3000 exposed
- db (image: mysql:5.7)
- wordpress (image: wordpress:latest)
  - port 8000 exposed
```

So I can access the wordpress dashboard with `http://localhost:8000/wp-admin` or the frontend with `http://localhost:3000` **on my host machine**.

Therefore I specified `NEXT_PUBLIC_WORDPRESS_URL=http://localhost:8000` in `.env`.
CSR works well in this settings, but SSR does not.
This is because in the frontend container we cannot access the wordpress with `http://localhost:8000`. In the container we should use `http://wordpress` instead. When we access with `http://localhost:8000`, the frontend shows an error like `Error: request to http://localhost:8000/graphql failed, reason: connect ECONNREFUSED 127.0.0.1:8000`.

I tried to fix this by defining two env variables like:
```
WORDPRESS_URL=http://wordpress
NEXT_PUBLIC_WORDPRESS_URL=http://localhost:8000
```

And re-writing config files like:
`faust.config.js`
```
export default coreConfig({
  wpUrl: process.env.WORDPRESS_URL || process.env.NEXT_PUBLIC_WORDPRESS_URL,
  apiClientSecret: process.env.WP_HEADLESS_SECRET,
});
```

`gqty.config.js`
```
const config = {
  react: false,
  scalarTypes: { DateTime: 'string' },
  introspection: {
    endpoint: `${process.env.WORDPRESS_URL || process.env.NEXT_PUBLIC_WORDPRESS_URL}/graphql`,
    headers: {},
  },
  destination: './src/client/index.ts',
  subscriptions: false,
  javascriptOutput: false,
};
```

In my environment these settings make the frontend hang up. `localhost:3000` does not respond, no errors, nothing happens.

My question is, are there any way to specify separate URLs for CSR and SSR?

**Comment by blakewilson** [comment]
@m1kit 👋 

This is not currently supported in Faust.js.

Some way to support a seperate SSR/SSG URL may be helpful for situations where Docker is involved. Possibly through a `config` key. We will look into this further.

**Comment by m1kit** [comment]
> Some way to support a seperate SSR/SSG URL may be helpful for situations where Docker is involved. Possibly through a `config` key. We will look into this further.

That'd be helpful. Thank you.
