### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by Bowriverstudio** [wpengine/faustjs#660]
When I upgraded from 

From
```
"@faustjs/core": "^0.12.3",
 "@faustjs/next": "^0.12.3",
```

To

```
"@faustjs/core": "^0.13.1",
"@faustjs/next": "^0.13.1",
```

I got this error: 

Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Fixed it by changing 
`import { HeadlessProvider } from "@faustjs/next";`
To
`import { FaustProvider } from "@faustjs/next";`

Would it be possible to update: https://faustjs.org/docs/release-notes. 

Thank you.

**Comment by blakewilson** [comment]
Hey @Bowriverstudio 👋 

This is resolved now. At the time, it looks like some of our changes were not deployed to faustjs.org.

Additionally, we've added new changelogs that should better define each release and their changes:

- @faustjs/core changelog: https://faustjs.org/docs/changelog/core
- @faustjs/next changelog: https://faustjs.org/docs/changelog/next
- @faustjs/react changelog: https://faustjs.org/docs/changelog/react
- FaustWP plugin changelog: https://faustjs.org/docs/changelog/faustwp
