### ISSUE TITLE
Bug: [ERR_UNSUPPORTED_DIR_IMPORT] error when following the tutorial and trying to run the build/dev

### ISSUE THREAD

**Issue by macemmek** [wpengine/faustjs#696]
I was following the tutorial until https://faustjs.org/docs/tutorial/querying-data#get-posts-using-useposts-hook but I failed when trying to run dev or build with data from local WP.

```
npm run build

> build
> next build

info  - Loaded env from /Users/przemek/WebDev/projects/myapp/.env.local
info  - Checking validity of types  
info  - Creating an optimized production build  
info  - Compiled successfully
info  - Collecting page data .node:internal/process/promises:246
          triggerUncaughtException(err, true /* fromPromise */);
          ^

Error [ERR_UNSUPPORTED_DIR_IMPORT]: Directory import '/Users/przemek/WebDev/projects/myapp/node_modules/@faustjs/core/dist/mjs/gqty' 
is not supported resolving ES modules imported from /Users/przemek/WebDev/projects/myapp/node_modules/@faustjs/core/dist/mjs/export/index.js
    at new NodeError (node:internal/errors:371:5)
    at finalizeResolution (node:internal/modules/esm/resolve:390:17)
    at moduleResolve (node:internal/modules/esm/resolve:915:10)
    at defaultResolve (node:internal/modules/esm/resolve:1005:11)
    at ESMLoader.resolve (node:internal/modules/esm/loader:475:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:245:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:79:40)
    at link (node:internal/modules/esm/module_job:78:36) {
  type: 'Error',
  code: 'ERR_UNSUPPORTED_DIR_IMPORT',
  url: 'file:///Users/przemek/WebDev/projects/myapp/node_modules/@faustjs/core/dist/mjs/gqty'
}
```

I'm not sure if the error has something to do with the app or WP or rather the dependencies. Or I am missing something...

## Applicable Versions

- `@faustjs/core` version: 0.14.1
- `@faustjs/next` version: 0.14.0
- WordPress version: 5.8.2
- node -v: 17.2.0, 16.13.1, MacOS

## Steps To Reproduce

1.Follow the tutorial until https://faustjs.org/docs/tutorial/querying-data#get-posts-using-useposts-hook
2.Run npm run dev or npm run build

## The current behavior

Build/Dev fails with [ERR_UNSUPPORTED_DIR_IMPORT]

## The expected behavior

Build/Dev should run successfully.

**Comment by blakewilson** [comment]
This is being caused by the use of Next.js 12 in your project.

We have a PR (#667) that adds support for Next.js 12 that we intend to release next week. In the meantime, downgrading to Next.js 11 in your `package.json` file will fix this 👍

**Comment by macemmek** [comment]
Thanks, I couldn't find it by the error message as it was just on the attached screenshot. 🙂
