### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by Pavithranvel1** [wpengine/faustjs#781]
How to remove http only cookie from faust js front end, once if we logged out from wordpress dashboard

**Comment by cfg-fadica** [comment]
Faust JS has its own authentication and does not use the cookie set by WordPress. Logging in and out of the front end does not affect authentication to the backend and vice versa.

https://faustjs.org/docs/next/guides/auth

**Comment by blakewilson** [comment]
Yes @cfg-fadica is correct, the WordPress admin and Faust.js frontend both use two different cookies. Therefore, logging out of the WordPress admin will not necessarily log you out of the Faust.js frontend.

If you want to specifically log out of the Faust.js frontend, you can leverage the [`useLogout`](https://faustjs.org/docs/next/reference/hooks/useLogout) hook.
