### ISSUE TITLE
Repeater in acf

### ISSUE THREAD

**Issue by Pavithranvel1** [wpengine/faustjs#789]
How can we get the repeater field type in useQuery() for the faustjs typescript but I can fetch group, text, images etc.,
Please provide any solutions regarding this.
Thank you

**Comment by josephfusco** [comment]
Hey @Pavithranvel1, thanks for the feedback! We have added a ticket for investigating support with the ACF repeater field!

**Comment by theodesp** [comment]
I'm closing this issue since we are not working on old Faust at the moment. We will revisit certain ACF features and compatibility with new Faust.
