### ISSUE TITLE
Clarify NextJS SSG docs

### ISSUE THREAD

**Issue by MichaelAllenWarner** [wpengine/faustjs#807]
Somewhere in [this section of the docs](https://faustjs.org/docs/next/guides/ssr-ssg#ssg-using-getnextstaticprops), it might be worth clarifying that any _queries_ you want handled statically during the build (as opposed to dynamically on the client-side) need to be executed in `getStaticProps()` as usual (e.g., with `client.client.inlineResolved()` and `GQty`'s `prepass()` helper) rather than in the component with hooks. An example with that pattern would be nice, too.

**Comment by MichaelAllenWarner** [comment]
Relatedly, I wonder: could one do what I said above (run the query during build in `getStaticProps()` so that the component renders the data immediately on mount) _and also_ use Faust/GQty hooks in the component to run the _same_ query on the client-side after mount (i.e., to update the SSG content in real time if it's out of date)?

The use-case I'm thinking of is a site that's configured to rebuild/redeploy whenever content is updated on the WP side. It might take a few minutes for the new build to make it live, and the (non-dev) person who updated the content might be eager to see their updates on the real site. An update-on-the-fly-if-needed mechanism would let them do that right away, without sacrificing the benefits of SSG-queries. There'd be a flash of content if the updated stuff is above the fold, but that would disappear in a few minutes once the deploy finishes.

I bet this is doable, and it strikes me as the sort of thing that's probably worth documenting. In general, I think the SSG/SSR docs page would benefit from a few more examples.

**Comment by blakewilson** [comment]
@MichaelAllenWarner 👋 

Could you please clarify what kind of examples you'd like to see?

To your first point, you can indeed execute queries statically outside of `getStaticProps`. For example:

```tsx
import { GetStaticPropsContext } from 'next';
import { getNextStaticProps } from '@faustjs/next';
import { client } from 'client';

export default function MyPage() {
  const { usePosts } = client;

  return (
    <>
      <h2>Recent Posts</h2>
      {usePosts()?.nodes.map((post) => (
        <li key={post.id}>{post.title()}</li>
      ))}
    </>
  );
}

export async function getStaticProps(context: GetStaticPropsContext) {
  return getNextStaticProps(context, {
    Page: MyPage,
    client,
  });
}
```

The following code will get your recent posts and generate a static page listing them with no client side requests. This method does not require `inlineResolved` or `prepass`. The only time you may see this data cascade to a client side request is if you have [data selections behind conditionals.](https://gqty.dev/docs/react/troubleshooting#data-selections--conditionals)

To your second point, we are looking into how we could achieve this. Next.js has recently released [On-Demand ISR](https://nextjs.org/blog/next-12-1#on-demand-incremental-static-regeneration-beta), which theoretically means we could purge/revalidate a page when the WordPress content has changed. We're still looking into this, but if you want to engage further we have a discussion thread for this: https://github.com/wpengine/faustjs/discussions/842

**Comment by MichaelAllenWarner** [comment]
@blakewilson 

Thanks for the response! I was using `useQuery` and finding that no query-results appeared on the page until after a client-side fetch. I think that what you said about data selections being behind conditionals was likely the issue.

My project is entirely SSG (no SSR, and really no client-side fetching needed, either), and ever since I encountered the "issue" I documented here, I've just been doing the `client.client.resolved`/`prepass` thing in `getStaticProps` (without bothering with `getNextStaticProps` at all), and that seems to be doing the trick. For this simple case, is there any reason that I _should_ switch to `useQuery` / `getNextStaticProps`? I'm unclear on whether there'd be any benefits to that for just build-time queries.

**Comment by blakewilson** [comment]
@MichaelAllenWarner Thanks for the clarification.

Technically, both of these solutions will provide the same end result, so if you prefer doing data fetching with `resolved`/`prepass`, feel free!

However, I believe you'll experience less boilerplate and not need to specify specific fields using `prepass` if you use `getNextStaticProps` (provided you don't run into the data selections behind conditionals issue). If you take a look at our [getting started example](https://github.com/wpengine/faustjs/tree/canary/examples/next/getting-started), the whole app is SSG using `getNextStaticProps`.

**Comment by MichaelAllenWarner** [comment]
@blakewilson 

Thanks for that. Yes, having to specify the desired fields with `prepass` is a bit of a chore.

Does the `getNextStaticProps`/`useQuery` technique trigger a client-side query on "mount"? Or was I only seeing that behavior because I broke things with the conditional data-selections?

**Comment by blakewilson** [comment]
@MichaelAllenWarner That was likely because you had a conditional data selection. The proper implementation of `getNextStaticProps` with `useQuery` will result in all queries being triggered server side, then statically generated, until the next `revalidate` timer has lapsed. By default, this is set to 15 minutes in Faust.js: 

https://faustjs.org/docs/next/guides/ssr-ssg#setting-up-incremental-static-regeneration-isr

So, if you were to take a look at your network requests, you should see no requets to the `/graphql` endpoint in WordPress.

**Comment by blakewilson** [comment]
@MichaelAllenWarner I'm going to close this since the original intention of the issue seems to have been addressed. If I'm incorrect, please feel free to open a new issue 👍
