### ISSUE TITLE
Bug: local auth inconsistent invalid request with useLogin() when deployed to vercel or using vercel dev locally

### ISSUE THREAD

**Issue by joshuagageellis** [wpengine/faustjs#815]
## Applicable Versions

- `@faustjs/core` version: 0.15.4
- `@faustjs/react` version: 
- `@faustjs/next` version: 0.15.5
- WordPress version: 5.9.2

## Steps To Reproduce
The authentication was working on WPE Atlas, but when testing deploys on Vercel the authentication request returns inconsistent failures. My best guess is there is an issue setting the cookie on serverless infrastructure.

- WordPress is running Faust Plugin on WPE hosting
- Issue does not happen on WPE, nor on `npm run start` locally
- Issue happens on deployed Vercel and `vercel dev` locally
- Error source is `accessToken.js`

I added some console logs to the package, this is what I am getting back when attempting log in:
<img width="931" alt="Screen Shot 2022-03-17 at 2 23 18 PM" src="https://user-images.githubusercontent.com/25233830/158870385-d50d31a4-4b4a-4286-b223-8d02ce6f8526.png">

Link to code example:

The login component for reference.
```
export default function LoginForm() {
  const router = useRouter();
  const { useLogin } = client.auth;
  const { login, data, error } = useLogin();

  let initValues = {
    userNameOrEmail: '',
    password: '',
  }

  useEffect(() => {
    if (!router.query.redirect_uri) {
      router.push(
        {
          pathname: appConfig.loginPath,
          query: { redirect_uri: appConfig.dashboardPath }
        },
        undefined,
        { shallow: true }
      );
    }
  }, [router]);

  const errorMessage = data?.error || error?.message;

  return (
    <Formik
      initialValues={initValues}
      validationSchema={Yup.object({
          userNameOrEmail: Yup.string().required('Required'),
          password: Yup.string().required('Required'),
				})
			}
      onSubmit={(values) => {
        login(values.userNameOrEmail, values.password)
          .then((resp) => {
            console.log(resp);
          })
          .catch(err => {
            console.log(err);
          });
      }}
    >
      <Form>
        <LFFieldGroup errorMsg={errorMessage} />
      </Form>
    </Formik>
  );
}
```

**Comment by joshuagageellis** [comment]
Sorry didnt do the submission process appropriately so closed my request. My bad.

The issue was corrected by adding:
```
  if (isString(code) && code.length > 0) {
    url += `?code=${code}`;
    url += `?code=${encodeURIComponent(code)}`;
  }
  ```
  to `packages/core/src/auth/client/accessToken.ts`

**Comment by theodesp** [comment]
@joshuagageellis Thank you. We are planning to merge an example with local authentication as well.

https://github.com/wpengine/faustjs/pull/770/files#diff-1b8144d8e3c8f81d49ace8af9f7cffa33ba10c9d337c7b1ec8e7ca116ac4a31f


I will close this issue for now.

**Comment by theodesp** [comment]
I'm closing this issue. You can follow the updates in: https://github.com/wpengine/faustjs/issues/1471
