### ISSUE TITLE
Bug:  	Undefined property: WP_Post_Type::$graphql_single_name

### ISSUE THREAD

**Issue by esilverman682** [wpengine/faustjs#829]
I updated the Faustjs Plugin but still getting this error using the Query Monitor Plugin for Wordpress 

**Undefined property: WP_Post_Type::$graphql_single_name**

Nextjs frontend working fine. But clicking on navigation links causes stress on server and major slowdowns on the Wordpress Dashboard "Connection lost" error sometimes.

**Comment by theodesp** [comment]
@esilverman682 We have yet to update the FaustWP plugin this week as we had some prior tasks to finish on a new product launch we were working on.

**Comment by esilverman682** [comment]
Ok Thank you.

**Comment by blakewilson** [comment]
Hi @esilverman682, this fix should now be in [faustwp@0.7.7](https://wordpress.org/plugins/faustwp/#developers). Please let us know if you are still experiencing this after updating.
