### ISSUE TITLE
Bug: Conditional values not working with applyRequestContext

### ISSUE THREAD

**Issue by humet** [wpengine/faustjs#845]
I have been trying to get Faust working with a Wordpress API that is using basic auth password protection. I am using `applyRequestContext` to add the required authentication headers to each request. 

Everything works fine until I need to fetch data on the client-side. When that happens I start to get CORS errors with the request. 

I have forced the title in a minimal repo to be conditionally fetched which is causing that part to be fetched on the client-side. The same error occurs when we are trying to do 'infinite' post loading etc. 

## Applicable Versions

- `@faustjs/core` version: 0.15.4
- `@faustjs/react` version:
- `@faustjs/next` version: 0.15.5
- WordPress version: 5.9.2

## Steps To Reproduce

1. Download and install https://github.com/Dexerto/basic-auth-faust-example
2. Change NEXT_PUBLIC_WORDPRESS_URL in .env.local to `https://blankdexsitstg.wpengine.com`
3. Load homepage
4. Look at Network Requests

Link to code example: https://github.com/Dexerto/basic-auth-faust-example/blob/6f43604d2ba1e99236dd1903aaaa656eb042c0c7/src/pages/index.tsx#L22

## The current behavior

![Screenshot 2022-04-20 at 15 09 52](https://user-images.githubusercontent.com/3963951/164249702-ef226325-5e82-4d95-a402-347ddafa9065.png)

![Screenshot 2022-04-20 at 15 09 56](https://user-images.githubusercontent.com/3963951/164249731-cb472d71-2ac9-4d03-8133-f1e9d477476c.png)

## The expected behavior

Fetch completes successfully.

**Comment by theodesp** [comment]
@humet Thank you for reporting this issue.I've created a ticket in our internal system to look into this problem. We will post any updates in this thread.
