### ISSUE TITLE
Bug: /generate link are not supported in sub-folder

### ISSUE THREAD

**Issue by yanmorinokamca** [wpengine/faustjs#850]
## Applicable Versions

faustjs plugin

- WordPress faustwp version: 0.7.6

## Steps To Reproduce

1. With a bedrock installation, wordpress is inside the /wp folder. Nextjs will call https://domain.com/wp/graphql, and will also try to call https://domain.com/wp/generate. In bedrock installation, HOME_URL is https://domain.com   and SITE_URL is https://domain.com/wp
2. When calling /wp/generate,  the current regexp in the function handle_generate_endpoint ( includes/auth/callbacks.php ) doesn't support sub-folder.

## Patch
```php
    public function parseRequest()
    {
        // not tested with WPML language subdomain
        $url = site_url('/generate', 'relative'); // with the beginning and ending slash
        $matchUrl = '/^' . preg_quote($url, '/') . '/';

        if ( ! preg_match( $matchUrl, $_SERVER['REQUEST_URI'] ) ) { // phpcs:ignore WordPress.Security
            return;
        }
    
        if ( empty( $_GET['redirect_uri'] ) ) { // phpcs:ignore WordPress.Security
            return;
        }
    
        $redirect_uri = wp_unslash( $_GET['redirect_uri'] ); // phpcs:ignore WordPress.Security
    
        if ( ! is_user_logged_in() ) {
            wp_safe_redirect(
                wp_login_url( $url . '/?redirect_uri=' . rawurlencode( $redirect_uri ) )
            );
    
            exit;
        }
    
        $auth_code = generate_authorization_code(
            wp_get_current_user(),
            MINUTE_IN_SECONDS * 1
        );
    
        $redirect_uri = add_query_arg( 'code', rawurlencode( $auth_code ), $redirect_uri );
    
        wp_safe_redirect( $redirect_uri );
    
        exit;
    }
```

This patch change the preg_match and wp_login_url function calls with a more generic "/<prefix>generate" part using site_url.

**Comment by josephfusco** [comment]
Hey @yanmorinokamca thanks for the feedback! We have added a ticket for this to our backlog!
