### ISSUE TITLE
acf fields returns null on preview

### ISSUE THREAD

**Issue by bebjakub** [wpengine/faustjs#882]
[contentNode](https://github.com/wpengine/faustjs/blob/c74ce4f80f933ab73ffed43697d32e35d0b40311/packages/next/src/gqty/hooks/usePreviewNode.ts#L57)'s [acf fields](https://github.com/wp-graphql/wp-graphql-acf) returns null on preview, although on regular post page returns values.
## Applicable Versions

- `@faustjs/core` version: 0.15.6
- `@faustjs/next` version: 0.15.6
- WordPress version: 5.9.3

**Comment by blakewilson** [comment]
Hi @bebjakub,

Could you please post an example of the query/code you are using to get preview data in ACF?

Also, this ACF WPGraphQL PR may have some helpful context:
https://github.com/wp-graphql/wp-graphql-acf/pull/153

**Comment by bebjakub** [comment]
@blakewilson Sorry for the delay, but It's working already.
