### ISSUE TITLE
Bug: Support for safari ios 12

### ISSUE THREAD

**Issue by marie-maxime** [wpengine/faustjs#903]
It seems like faust js is not working on ios 12.

Output error: `SyntaxError: Unexpected token '?'`

NextJS supports older browsers including IE 11 and previous version of safari. I would expects faustjs to work on ios 12.

It seems like the issue is coming from a missing transpiling with optionnal chaining (`?.`)

## Applicable Versions

- `@faustjs/core` version: 0.15.6
- `@faustjs/react` version: 0.15.6
- `@faustjs/next` version: 0.15.6
- WordPress version: latest
- node: v16.14.0

## Steps To Reproduce

1. Clone starter project with faust.
```
npx create-next-app \
    -e https://github.com/wpengine/faustjs/tree/main \
    --example-path examples/next/getting-started \
    --use-npm \
    my-app
```
2. Start the project and open it in ios 12 safari ( I used browserstack). The error will be visible in the console.

## The current behavior
Faustjs crash on ios 12 & 13.

## The expected behavior
Faustjs should follows NextJS supported browser and works on ios 12.

**Comment by josephfusco** [comment]
Hey @marie-maxime thanks for reporting this issue!

We have created a ticket in our internal backlog for this ([MERL-332](https://wpengine.atlassian.net/browse/MERL-332)). Will post back once we have more info!

**Comment by marie-maxime** [comment]
Thank you for fixing this and addressing it as quickly! 👍
