### ISSUE TITLE
How to show a loading bar with SSR?

### ISSUE THREAD

**Issue by cobrani** [wpengine/faustjs#911]
Hi! In my project, I'd like to do two things:
- Enable SSR, but don't do static site generation during build time
- Show something (e.g. loading bar) to the user when page including wordpress data is being loaded (when switching pages in client)

So far, for SSR I've noticed the usage of `getNextStaticProps` and `getNextServerSideProps` . To check if the page is loading, I am using `useQuery().$state.isLoading` - but this is always false when using one of the methods. Sure, this is because the fetching is done in SSR, but I don't want to do this when the user is switching pages in browser and have the possibility to show some bar while ensuring the page is fully rendered for direct requests coming from Google etc.
How can I achieve this?

**Comment by theodesp** [comment]
Hello @cobrani. Not sure what you are asking is possible. Within SSR the client waits for the server to provide and page props and any queries done in `getNextServerSideProps` are only populating the cache with props. In the client side, any calls to `useQuery` will fetch data from the cache that was already populated when the page loads.

What you are looking for is [Suspense in SSR which is not supported currently](https://gqty.dev/docs/react/suspense#suspense--ssr).

There is one answer in SO about loading pages in Next.js that you might consider though:

https://stackoverflow.com/questions/69263469/next-js-getserversideprops-loading-state

**Comment by cobrani** [comment]
Hey @theodesp! Thanks a lot for your answer. It seems that I'll also use the hooks like it is referred in the SO post. So if pages are not in the cache, I can use `routeChangeStart` etc. For testing, I just included https://www.npmjs.com/package/nextjs-progressbar and it worked quite well, so I'll close this for now. Thanks

However, I'll investigate as I'm not that familiar with state and cache handling in next js yet (for reference, I am coming from frontity framework - the tight coupling of the framework with WP and missing new updates have led me here :-) )
