### ISSUE TITLE
Bug: Issue with Amplify (AWS) - redirect 307 in every page

### ISSUE THREAD

**Issue by roeean** [wpengine/faustjs#948]
## Applicable Versions

- `@faustjs/core` version: 0.15.7
- `@faustjs/next` version: 0.15.7
- WordPress version: 6.0.1

## Steps To Reproduce

1. Uploading the code to amplify

Link to code example:
https://github.com/roeean/nextfaust/tree/brnch2

link to my amplify site:
https://brnch2.d1v8cokucx8cjb.amplifyapp.com/

## The current behavior

Every page you try to access is directed (HTTP 307) to the /preview page.

## The expected behavior

get the page properly as if running in a local environment

## Description

hi,

I created a website based on your package, which works perfectly with headless WordPress. When I ran my program on a local server (localhost) everything worked properly, but as soon as I uploaded it to amplify, every page they try to access is redirected (HTTP 307) to the "/preview" page.

I thought it was a problem related to the preview setting so I simply deleted it and uploaded the program again, but the reference remained.

To understand if this is a problem with my code, I uploaded to amplify the Start code example that you published on your website, but in this case too - the same problem.

I asked for help from AWS, but according to them, whoever creates these 307 redirects is one of the packages. In the example code you uploaded, there are no more packages in package.json, so the problem is probably in your plugin.

I would appreciate it if there is a way to solve this problem.

Thank you in advance.

![image](https://user-images.githubusercontent.com/85000486/181261804-dd7d1a77-33aa-434b-9be0-a62036807230.png)

**Comment by roeean** [comment]
Link to code example:
https://github.com/roeean/nextfaust/tree/brnch2

link to my amplify site:
https://brnch2.d1v8cokucx8cjb.amplifyapp.com/

**Comment by theodesp** [comment]
Hello @roeean . Thank you very much for your interest in Faust. I will create a new ticket in our backlog to investigate as I was able to verify this issue with your link. 
I noticed that you used a custom `previewDestination` which I believe there is a different kind of a bug there. Could you deploy the app without this setting and check again please? I think you also need to create a `preview.tsx` component as well
https://faustjs.org/docs/next/guides/post-page-previews

**Comment by theodesp** [comment]
Thank you. I will try to reproduce in Amplify as it seems platform specific

**Comment by roeean** [comment]
Thank you @theodesp, I appreciate your help. Would you like that I send you (privately) my credentials to Amplify?

**Comment by theodesp** [comment]
Hey @roeean I tried to deploy the example getting started project on Amplify using this guide but I'm having issues
https://docs.aws.amazon.com/amplify/latest/userguide/server-side-rendering-amplify.html. I've logged a ticket into their platform.

It would be great if you send me a new user credentials with read access only for Amplify  so I can check the environment. You can send this via discord or any other secure method you have
https://discord.com/channels/836253505944813629/877940107016019998

**Comment by theodesp** [comment]
https://discord.com/invite/J2khkF9XYK

**Comment by roeean** [comment]
> https://discord.com/invite/J2khkF9XYK

I sent you. Thank you!

**Comment by theodesp** [comment]
Hey @roeean I've sent you a message in discord regarding the appID

**Comment by roeean** [comment]
Hi, I found the problem.

There is a known issue with Amplify, which ignores any "has" condition in the redirects function of `next.config.js`.
Source: https://github.com/aws-amplify/amplify-hosting/issues/2593

The `withFaust()` function adds the following redirect rule to the config object:
```
   {
        source: '/((?!preview).*)',
        has: [{
          type: 'query',
          key: 'preview',
          value: 'true'
        }],
        destination: '/preview',
        permanent: false
   }
```
But Amplify, which ignores the data under the "has" key, performs a redirect for every request, even without `preview=true` in the query.

When I remove the `withFaust()` function from `next.config.js` - the site works well, but it prevents me from using the preview mode.

Do you have an idea how to solve this?

Thank you in advance!

**Comment by theodesp** [comment]
Hey @roeean thats unfortunate. Amplify must be doing something wrong to break nextjs there. What you can do is maybe don't use `withFaust` now as it only creates this redirect rule. You won't be able to use previews directly but you can still use them indirectly. You will have to manually enter the preview path url. For example you will have to prepend the preview path:

**Preview path from Wordpress:**
`http://localhost:3000/?page_id=3&preview=true&p=3&typeName=Page`

**Preview path in Headless:**
`http://localhost:3000/preview?page_id=3&preview=true&p=3&typeName=Page`


Note that this option should be temporary until Amplify fixes the issue.

**Comment by roeean** [comment]
Hi @theodesp,

I solved it with the following method by adding the following code to [...pageUri].js & index.js:

```
  const router = useRouter();
  if (router.query.preview) {
    const { p, page_id, typeName } = router.query;
    router.push(`preview?page_id=${page_id || p}&preview=true&p=${p}&typeName=${typeName}`);
    return null;
  }
```

It's not the best solution, but it does the job until Amplify takes care of the problem.

Thank you very much for your kind help, I appreciate it!
If you need to, I would be happy to take part and help your team in the project :)

**Comment by theodesp** [comment]
Awesome. Thank you very much @roeean. If it's alright with you I will close this ticket and add a monitor for the Amplify issue

**Comment by theodesp** [comment]
@roeean I was wondering if Amplify is the right platform for Next.js given that it doesn't support Next.js v12 fully 
https://github.com/aws-amplify/amplify-hosting/issues/2343

**Comment by roeean** [comment]
> Awesome. Thank you very much @roeean. If it's alright with you I will close this ticket and add a monitor for the Amplify issue

Yes it's ok, thank you!
