### ISSUE TITLE
Bug: 504 GATEWAY_TIMEOUT ERROR

### ISSUE THREAD

**Issue by vkalyaanasundaram** [wpengine/faustjs#950]
Next.js application, we have created all pages as a static generation. Whenever I am navigating to the page (Ex: Blogs) I am able to see the content without any problems. But when I checked my browser console I was able to see "504 GATEWAY_TIMEOUT ERROR". Jason. Kindly help us to fix console error.

<img width="691" alt="console-error" src="https://user-images.githubusercontent.com/82804146/181771691-6c099fc2-0a67-46de-8f86-e97a0e8162cf.PNG">

**Comment by mveer08** [comment]
Facing same issue. Gets timeout

**Comment by theodesp** [comment]
Closing due to innactivity.
