### ISSUE TITLE
Bug: Previews always return Post not found

### ISSUE THREAD

**Issue by dawnerd** [wpengine/faustjs#999]
## Applicable Versions

- `@faustjs/core` version: 0.15.7
- `@faustjs/react` version: 0.15.7
- `@faustjs/next` version: 0.15.8
- WordPress version: 6.0.2

## Steps To Reproduce

1. Use quickstart guide https://faustjs.org/docs/next/getting-started#on-macos-linux-or-wsl-bash
2. Setup wordpress plugin: front end domain to match nextjs app, checked all of the feature checkboxes
3. Enabled graphql public introspection and ran the generate script, then disabled
4. Set up .env.local with headless secret key
5. Create new post or edit existing and hit preview in new tab

Link to code example:

No public code but I can provide someone on the team access to my repo / wordpress if that helps.

I did add a bunch of logging in the preview.tsx and nothing really stood out obvious there, there's nothing outdated when running npm outdated. The rest of the site content loads just fine so graph is working. It's not behind a cdn or using any custom post types. 

Output of `console.log(node)` on line 10 of preview.tsx

<img width="658" alt="image" src="https://user-images.githubusercontent.com/24781/188688049-868900fd-6580-4ce1-9cfd-1b187a1e0af7.png">

I've also manually run a graphql query to see if the revision was even generated and it does come back with isPreview: true and all

## The current behavior

Page does the redirect login flow and does set the auth cookie and confirmed the auth works via the auth hook on another page. End redirect shows loading briefly then post not found.

## The expected behavior

The preview of the page

---

If there's anything I could do to debug this further I'd love to give it a crack.

**Comment by theodesp** [comment]
Hello @dawnerd. Can I ask: did you set the permalink structure?
https://faustjs.org/docs/next/getting-started#setting-your-permalinks

**Comment by dawnerd** [comment]
Yep, have it set up exactly that way

**Comment by theodesp** [comment]
Hello @dawnerd. Thank you. We might need more information here about this as we cannot reproduce it. 

Is it possible to Is it possible to replicate this flow using Chrome Recorder tool?

https://developer.chrome.com/docs/devtools/recorder/

You will have to enable recording as shown in the guide and perform the interactions. Once you hit the 524 take a screen shot and export the recording as JSON and share it here:

<img width="1792" alt="175001868-9afe86fa-f3ae-49cb-b6fb-6d2b9c2ca384" src="https://user-images.githubusercontent.com/328805/189630309-5b2f41c6-5f7d-4a61-b904-78c6a1b077ab.png">

Can I also get more information about the deployment server for example:

Provider: (ex AWS, Netlify, Vercel or custom server)

Is the preview page trying to render a CPT that is not registered?

https://github.com/wpengine/faustjs/blob/canary/examples/next/getting-started/src/pages/preview.tsx#L18-L29
